/**
 * This file is the template for all other languages
 */

export default {
 global: {
  name: 'Webová aplikace Faithful',
  logout: 'Odhlásit se',
  login: 'Přihlásit přes Discord',
  ends_success: 'Povedlo se!',
  loading: 'Načítám, prosím vyčkejte…',
  no_results: 'Žádné výsledky',
  nyi: 'Zatím neimplementováno',
  translations: 'Translations',
  snackbar_system_theme: {
   sentence: 'Systémový motiv změněn na %s',
   themes: {
    title: 'Theme',
    light: 'světlý',
    dark: 'tmavý',
    system: 'System',
   },
  },
  btn: {
   add: 'Přidat',
   add_download: 'Přidat odkaz ke stažení',
   submit: 'Odeslat',
   submit_and_approve: 'Submit and approve',
   cancel: 'Zrušit',
   close: 'Zavřít',
   save: 'Uložit',
   edit: 'Upravit',
   delete: 'Smazat',
   ok: 'OK',
   yes: 'Ano',
   deny: 'Zamítnout',
   approve: 'Schválit',
   archive: 'Archive',
   load_more: 'Načíst více',
   discard: 'Discard',
   confirm: 'Confirm',
   publish: 'Publish',
   save_draft: 'Save as draft',
  },
  tabs: {
   general: {
    title: 'general',
    subtabs: {
     dashboard: 'nástěnka',
     profile: 'profil',
     statistics: 'statistiky',
     gallery: 'galerie',
    },
   },
   addons: {
    title: 'doplňky',
    subtabs: {
     submissions: 'přihlášky',
     upload: 'nahrát',
    },
   },
   review: {
    title: 'schvalování',
    subtabs: {
     addons: 'doplňky',
     translations: 'překlady',
    },
   },
   posts: {
    title: 'posts',
    subtabs: {
     list: 'list',
     create: 'create',
    },
   },
   database: {
    title: 'databáze',
    subtabs: {
     contributions: 'příspěvky',
     users: 'uživatelé',
     textures: 'textury',
     packs: 'packs',
     files: 'soubory',
     mods: 'módy',
     modpacks: 'modpacky',
     settings: 'nastavení',
    },
   },
  },
  months: {
   jan: 'Led',
   january: 'Leden',
   feb: 'Úno',
   february: 'Únor',
   mar: 'Bře',
   march: 'Březen',
   apr: 'Dub',
   april: 'Duben',
   may_: 'Květen',
   // longer
   may: 'Kvě',
   jun: 'Čvn',
   june: 'Červen',
   jul: 'Čvc',
   july: 'Červenec',
   aug: 'Srp',
   august: 'Srpen',
   sep: 'Zář',
   september: 'Září',
   oct: 'Říj',
   october: 'Říjen',
   nov: 'Lis',
   november: 'Listopad',
   dec: 'Pro',
   december: 'Prosinec',
  },
 },
 database: {
  titles: {
   contributions: 'Příspěvky',
   contributors: 'Přispěvatelé',
   textures: 'Textury',
   users: 'Users',
   packs: 'Packs',
   add_user: 'Přidat nového přispěvatele',
   add_textures: 'Přidat nové textury',
   add_texture: 'Přidat novou texturu',
   add_pack: 'Add new pack',
   change_pack: 'Edit pack',
   add_submission: 'Add submission information',
   edit_submission: 'Edit submission information',
   add_use: 'Přidat nové využití',
   add_path: 'Přidat novou cestu',
   add_mc_version: 'Přidat novou verzi Minecraftu',
   change_path: 'Upravit cestu',
   change_use: 'Upravit využití',
   change_texture: 'Upravit texturu',
   change_user: 'Upravit přispěvatele',
   change_mc_version: 'Upravit verzi Minecraftu',
   confirm_deletion: 'Potvrdit smazání',
  },
  subtitles: {
   add_manually: 'Přidat ručně',
   add_new_contribution: 'Add a new contribution',
   clone_contribution: 'Clone the contribution',
   no_contributor_yet: 'No contributor yet',
   pack: 'Resource Packy',
   submissions: 'Submission information',
   github: 'GitHub',
   resource_packs: 'Filter by pack',
   channels: 'Discord channels',
   user: 'Uživatel',
   select_user_role: 'Vyber role uživatele',
   search: 'Vyhledat',
   texture_result: 'Výsledky textur',
   pack_result: 'Pack results',
   user_result: 'User results',
   contribution_result: 'Contribution results',
   import_json_data: 'Importovat JSON data',
   uses: 'Využití',
   paths: 'Cesta/y',
  },
  labels: {
   copy_json_data: 'Copied JSON data to clipboard',
   anonymous: 'Anonym',
   anonymous_explain:
    'Pokud je zatrženo, jméno uživatele bude zobrazeno jako "Anonym" a jeho skin nebude viditelný. Může být změněno pouze administrátory!',
   mcmeta: 'Animated',
   new_mc_version_edition: 'Edice, ke které bude verze přidána',
   new_mc_version_path: 'Verze cesty, ke které bude verze přidána',
   new_mc_version_name: 'Jméno nové verze',
   nameless: 'Beze jména',
   tagless: 'No tags added',
   add_textures_success: 'Textury byly úspešně přidány',
   add_version_success: 'Verze byla úspěšně přidána',
   add_new_user: 'Přidat nového uživatele',
   add_new_pack: 'Add new pack',
   add_new_texture: 'Přidat novou texturu',
   add_new_path: 'Přidat novou cestu',
   add_new_use: 'Přidat nové využití',
   add_edition_use: 'Add automatic %edition% use',
   add_texture: 'Přidat textury',
   add_mc_version: 'Přidat novou verzi Minecraftu',
   ask_deletion: 'Opravdu chceš smazat %s (%d)?',
   ask_submission_deletion: 'Do you want to delete submission information for %s (%d)?',
   close_on_submit: 'Close on submit',
   clear_on_save: 'Clear on save',
   user_role: 'Role uživatele',
   discord_id: 'Discord ID',
   pack_id: 'Pack ID',
   pack_name: 'Pack name',
   pack_tags: 'Pack tags',
   pack_resolution: 'Pack resolution',
   pack_logo: 'Pack logo URL',
   council_enabled: 'Enable council',
   contributor_role: 'Contributor role ID',
   time_to_results: 'Time to results',
   time_to_council: 'Time to council',
   channels: {
    submit: 'Submission channel',
    council: 'Council channel',
    results: 'Results channel',
   },
   github_org: 'Organization',
   github_repo: 'Repository',
   submission_reference: 'Reference pack',
   edit_submission: 'Edit submission information',
   invalid_url: 'This URL is not valid',
   new_submission: 'Enable submissions',
   edit_mc_version: 'Upravit verzi Minecraftu',
   one_contributor: 'Prosím vyber alespoň jednoho uživatele',
   select_user: 'Select user(s)',
   parse_json: 'Převést JSON na data',
   search_contributions: 'Vyhledat příspěvky',
   search_username: 'Vyhledat uživatelské jméno',
   search_texture: 'Vyhledat jméno textury',
   search_pack: 'Search packs',
   select_texture_tag: 'Vybrat druh textury',
   select_pack_tag: 'Filter by tag',
   username: 'Uživatelské jméno',
   uuid: 'UUID Minecraft profilu',
   texture_name: 'Jméno textury',
   texture_tags: 'Druh textury',
   texture_id: 'ID textury',
   texture_uses: 'Využití textury',
   use_name: 'Jméno využití',
   use_id: 'ID využití',
   use_edition: 'Edice využití',
   path: 'Cesta',
   path_id: 'ID cesty',
   versions: 'Verze',
   no_path_found: 'Pro toto využití nebyly nalezeny žádné cesty.',
   no_use_found: 'Pro tuto texturu nebyla nalezena žádná využití.',
   current_mc_version: 'Aktuální verze Minecraftu',
   new_mc_version: 'Nová verze Minecraftu',
   id_field_errors: {
    one_required: 'At least one texture ID or an ID range is required',
    incorrect_value: 'Incorrect texture %value% ID or ID range',
   },
   use_singular: 'Use',
   use_plural: 'Uses',
   path_singular: 'Path',
   path_plural: 'Paths',
  },
  hints: {
   pack_id_creation: 'A Pack ID can either be manually specified or automatically generated.',
   pack_id_editing: 'Changing a pack ID can break everything!',
   pack_reference: 'Pack to compare against in submission embeds.',
   submission_timings: 'Delays are measured in days.',
   github_required: "An edition can be left blank if it's not yet supported.",
   channel_ids: 'Enable Developer Mode and right click on a channel to get channel IDs.',
   texture_id: 'Změna ID textury může všechno rozbít!',
   use_id: 'Změna ID využití může všechno rozbít!',
   path_id: 'Změna ID cesty může všechno rozbít!',
   path_prefill: 'Enter this first to generate most fields!',
   path: 'Cesta by měla začínat od kořenového adresáře, např. assets/…',
   example_scenario: 'Změní všechny výskyty určité verze Minecraftu v databázi na nějakou jinou, např. 1.17 → 1.17.1',
   example_scenario_warn: 'Prosím nezapomeň aktualizovat všechny branche na GitHubu!',
  },
  messages: {
   deleting_use_will_delete_paths: 'Deleting the use will also delete all its paths.',
  },
 },
 review: {
  titles: {
   addons: 'Posoudit doplňky',
   translation: 'Posoudit překlady',
   pending: 'Čekající na schválení',
   denied: 'Zamítnuto',
   approved: 'Schváleno',
   archived: 'Archived',
  },
  deny_window: {
   title: 'Deny add-on',
   label: 'Napiš důvod…',
   rule: 'Může být udán jakýkoliv důvod',
  },
  labels: {
   pending: 'Momentálně nejsou žádné doplňky čekající na schválení!',
   denied: 'Momentálně nejsou žádné zamítnuté doplňky!',
   archived: 'There are currently no archived add-ons!',
   approved: 'There are current no approved add-ons!',
   load_approved: 'Načíst schválené doplňky',
  },
  addon: {
   titles: {
    authors: 'Autor/Autoři',
    description: 'Popis',
    links: 'Odkazy',
    options: 'Možnosti',
   },
   labels: {
    link: 'Odkaz',
    optifine: 'OptiFine',
    approved_by: 'Schváleno administrátorem',
    denied_by: 'Zamítnuto administrátorem',
    reason: 'Důvod',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Nahrát nový doplněk',
   edit: 'Upravit doplňky',
   submissions: 'Přihlášky',
   details: 'Podrobnosti',
  },
  remove: {
   title: 'Potvrdit smazání',
   labels: {
    question: 'Opravdu chceš smazat %s?',
    warning: 'Tuto akci nelze odvolat.',
   },
  },
  general: {
   loading_addon: 'Načítám doplněk…',
   rules: 'Make sure to read the add-on rules before submitting',
   title: 'Obecné',
   name: {
    label: 'Název doplňku',
    hint: 'Čím kratší, tím lepší. (Ale nepřežeň to!)',
    rules: {
     name_required: 'Název je vyžadován.',
     name_too_big: 'Název doplňku musí být kratší než %s znaků.',
     name_too_small: 'Název doplňku musí být alespoň %s znaků dlouhý.',
     name_unavailable: 'Tento název už je používán jiným doplňkem!',
    },
   },
   description: {
    label: 'Popisek doplňku',
    hint: 'Popisek můžeš vyšperkovat formátováním Markdown!',
    rules: {
     description_required: 'Popisek je vyžadován.',
     description_too_big: 'Popisek musí být kratší než %s znaků.',
     description_too_small: 'Popisek musí být alespoň %s znaků dlouhý.',
    },
   },
   embed_description: {
    label: 'Embed description',
    hint: 'Description seen when sharing the add-on on social media',
    rules: {
     too_big: 'Embed description must be less than %s characters.',
    },
   },
   slug: {
    label: 'Add-on slug',
    hint: 'Changing this will break old links!',
   },
   reason: {
    title: 'Update reason',
    text: 'Please tell us what you updated to make reviewing your add-on easier!',
    required: 'An update reason is required',
    bounds: 'Update reason must be between %s and %s characters long',
   },
   authors: {
    label: 'Vyber autory doplňku',
    hint:
     'Jakmile je doplněk nahrán, jakýkoliv autor ho může upravit! | Pokud v seznamu někoho nemůžeš najít, kontaktuj nějakého administrátora či vývojáře',
   },
  },
  images: {
   title: 'Obrázky',
   header: {
    labels: {
     drop: 'Kliknutím vyberte obrázek záhlaví',
     normal: 'Hlavní obrázek',
     replace: 'Změnit hlavní obrázek',
    },
    rules: {
     image_size: 'Velikost obrázku musí být méně než %s KB! (Ke kompresi můžeš využít https://compressor.io/.)',
     image_ratio: 'Nesprávný poměr stran: Nahraný obrázek musí mít poměr stran 16:9.',
     image_required: 'Hlavní obrázek je vyžadován.',
     jpeg: 'Image must be a lossy JPEG.',
    },
   },
   carousel: {
    labels: {
     drop: 'Kliknutím vyberte další obrázky',
     normal: 'Další obrázky',
     replace: 'Změnit další obrázky',
    },
    rule: 'Nesprávný poměr stran: Obrázky s poměrem stran jiným než 16:9 byly odstraněny.',
   },
  },
  options: {
   title: 'Možnosti',
   optifine: {
    label: 'Vyžaduje OptiFine',
   },
   editions: {
    label: 'Podporované edice',
    rule: 'Je nutno vybrat alespoň jednu edici.',
   },
   resolutions: {
    label: 'Podporovaná rozlišení',
    rule: 'Je nutno vybrat alespoň jedno rozlišení.',
   },
  },
  downloads: {
   title: 'Odkazy na stažení',
   name: {
    placeholder: 'Odkaz na CurseForge, GitHub…',
    label: 'Jméno',
    rules: {
     name_required: 'Jméno je vyžadováno.',
     name_cannot_be_empty: 'Jméno nemůže být prázdné.',
    },
   },
   link: {
    placeholder: 'https://www.příklad.cz/',
    label: 'Odkaz',
    rule: 'URL musí být platné.',
   },
  },
  status: {
   approved: 'Schváleno',
   denied: 'Zamítnuto',
   pending: 'Čeká na schválení',
  },
 },
 posts: {
  titles: {
   list: 'All posts',
   edit: 'Edit post',
   new: 'Create new post',
  },
  status: {
   published: 'Published',
   pending: 'Pending',
  },
  loading: 'Loading post…',
  general: {
   heading: 'General',
   title: {
    label: 'Post title',
    placeholder: 'Faithful Smart Fridge – Alpha 1',
   },
   permalink: {
    label: 'Permalink',
    placeholder: '/faithfulsmartfridge/A1',
   },
   header_img: {
    label: 'Header image (optional)',
    hint: 'Note: This must be uploaded separately',
    placeholder: 'https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Post release date',
    placeholder: 'YYYY-MM-DD',
   },
   description: {
    label: 'Post description',
    hint: 'You can use HTML markup to improve your description!',
   },
  },
  download: {
   heading: 'Downloads',
   add_category: 'Add download category',
   add_single_item: 'Add single download',
   category: 'Download category name',
   name: 'Download name',
   link: 'Download link',
   link_placeholder: 'https://www.example.com/',
  },
  changelog: {
   heading: 'Changelog',
   add_category: 'Add changelog category',
   add_item: 'Add changelog item',
   form_levels: {
    primary: 'Primary category',
    secondary: 'Secondary category',
    item_category: 'Item category (Authors)',
    item: 'Item (Authors)',
   },
  },
 },
 statistics: {
  title: 'Statistiky příspěvků',
  loading: 'Loading graph…',
  label: {
   textures: 'Textury',
   contributors: 'Přispěvatelé',
   contributions: 'Příspěvky',
  },
 },
 profile: {
  title: 'Profil',
  general: {
   title: 'Obecné',
   uuid: {
    label: 'UUID Minecraft profilu',
    hint: 'Your skin will be displayed with add-ons you authored.',
   },
   username: {
    label: 'Uživatelské jméno',
    hint: 'Tvoje uživatelské jméno bude využito na webových stránkách pro příspěvky, doplňky atd.',
   },
  },
  social: {
   title: 'Odkazy na sociální sítě',
   link_label: 'Edit link',
   type_label: 'Select media type',
   placeholder: 'https://www.příklad.cz/',
   add: 'Add social media',
  },
  save_changes: 'Save changes',
  delete: {
   title: 'Delete account',
   btn: 'Delete account',
   description: 'Are you sure you want to delete your account?',
   warning: 'This process is irreversible!',
  },
 },
 files: {
  general: {
   name: {
    label: 'Název souboru',
    hint: 'Název by měl soubor stručně popisovat.',
    rules: {
     name_required: 'Název je vyžadován.',
     name_too_big: 'Název souboru musí být kratší než %s znaků.',
     name_too_small: 'Název souboru musí být alespoň %s znaků dlouhý.',
    },
   },
   use: {
    label: 'Název užití souboru',
    hint: 'Stručně popisuje, jak je soubor využit',
    rules: {
     name_required: 'Toto pole nelze zanechat prázdné.',
     name_too_big: 'Název užití souboru musí být kratší než %s znaků.',
     name_too_small: 'Název užití souboru musí být alespoň %s znaků dlouhý.',
    },
   },
  },
 },
 gallery: {
  stretched_switcher: 'Full width view',
  share_link_copied_to_clipboard: 'Share link copied to clipboard',
  max_items_per_row: 'Max items per row',
  title: 'Galerie',
  loading_message: 'Načítám…',
  error_message: {
   texture_not_done: 'Textura chybí nebo byla schválně vynechána.',
   user_anonymous: 'Anonym',
   user_not_found: 'Neznámý uživatel',
   contribution_not_found: 'V databázi nebyli nalezeni žádní autoři!',
  },
  category: {
   search: 'Vyhledat',
   tag: 'Tag',
   mc_version: 'Minecraft verze',
   edition: 'Edice',
   pack: 'Pack',
  },
  sort: {
   name_asc: 'Name (A → Z)',
   name_desc: 'Name (Z → A)',
   id_asc: 'Texture ID (smallest → largest)',
   id_desc: 'Texture ID (largest → smallest)',
   contrib_desc: 'Recently Contributed',
  },
  tooltip: {
   modded: 'Modded Texture',
   mojang: 'Mojang Studios',
   ignored: 'Ignored Texture',
  },
  all: 'vše',
  latest: 'Latest',
  clear_cache: 'Clear Gallery Cache',
  result_stats_singular: '%COUNT% texture found in %SECONDS% seconds',
  result_stats_plural: '%COUNT% textures found in %SECONDS% seconds',
  modal: {
   no_contributions: 'No contributions found',
   tabs: {
    information: 'informace',
    authors: 'autoři',
   },
   info: {
    texture: 'Textura',
    uses: 'Využití',
    paths: 'Cesty',
   },
   data: {
    contribution_id: 'Contribution ID',
    date: 'Datum',
    authors: 'Autor/Autoři',
    id: 'ID',
    name: 'Jméno',
    tags: 'Kategorie',
    use_id: 'ID využití',
    use_name: 'Jméno využití',
    edition: 'Edice',
    texture_id: 'ID textury',
    path_id: 'ID cesty',
    resource_pack_path: 'Cesta v resource packu',
    mc_versions: 'Verze Minecraftu',
   },
  },
 },
 settings: {
  title: 'Nastavení',
  label: {
   edit_raw: 'Upravit surová JSON data',
   edit_editor: 'Upravit ve vizuálním editoru',
  },
 },
 dashboard: {
  welcome_user: 'Vítej, uživateli %USER%!',
  welcome: 'Vítej!',
  totals: {
   authors: 'autorů',
   contributions: 'příspěvků',
   last_day: 'contributions in the last 48 hours',
   last_week: 'příspěvků minulý týden',
   last_month: 'příspěvků minulý měsíc',
  },
  titles: {
   users: 'Users',
   addons: 'Add-ons',
   contribution_activity: 'Contribution Activity',
   contribution_stats: 'Contributions',
   profile: 'Profile',
  },
  addons: {
   submissions: 'Submissions',
   upload: 'Upload',
  },
  users: {
   total: 'uživatelů',
   total_anonymous: 'anonymních uživatelů',
   total_roles: 'rolí',
  },
  locale: {
   on: ' ',
   less: 'Více',
   more: 'Méně',
  },
 },
 missing_page: {
  title: 'Are you lost in The End?',
  description: "Unfortunately, the page you requested doesn't exist!",
  main_page: 'Try checking your spelling or going to the %main page% to find what you were looking for.',
 },
 datepicker: {
  year: 'Year',
  month: 'Month',
  day: 'Day',
 },
};
