/**
 * This file is the template for all other languages
 */

export default {
 global: {
  name: 'Faithful Webanwendung',
  logout: 'Abmelden',
  login: 'Über Discord anmelden',
  ends_success: 'Erfolgreich abgeschlossen',
  loading: 'Wird geladen, bitte warten…',
  no_results: 'Es wurden keine Ergebnisse gefunden',
  nyi: 'Not yet implemented.',
  translations: 'Translations',
  snackbar_system_theme: {
   sentence: 'System theme changed to %s',
   themes: {
    title: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
   },
  },
  btn: {
   add: 'Hinzufügen',
   add_download: 'Download hinzufügen',
   submit: 'Einreichen',
   submit_and_approve: 'Submit and approve',
   cancel: 'Abbrechen',
   close: 'Close',
   save: 'Speichern',
   edit: 'Bearbeiten',
   delete: 'Löschen',
   ok: 'OK',
   yes: 'Ja',
   deny: 'Ablehnen',
   approve: 'Genehmigen',
   archive: 'Archive',
   load_more: 'Mehr laden',
   discard: 'Discard',
   confirm: 'Confirm',
   publish: 'Publish',
   save_draft: 'Save as draft',
  },
  tabs: {
   general: {
    title: 'general',
    subtabs: {
     dashboard: 'dashboard',
     profile: 'Profil',
     statistics: 'Statistik',
     gallery: 'Gallery',
    },
   },
   addons: {
    title: 'add-ons',
    subtabs: {
     submissions: 'Einreichungen',
     upload: 'hochladen',
    },
   },
   review: {
    title: 'Überprüfen',
    subtabs: {
     addons: 'add-ons',
     translations: 'Übersetzungen',
    },
   },
   posts: {
    title: 'posts',
    subtabs: {
     list: 'list',
     create: 'create',
    },
   },
   database: {
    title: 'Datenbank',
    subtabs: {
     contributions: 'Beiträge',
     users: 'users',
     textures: 'Texturen',
     packs: 'packs',
     files: 'Dateien',
     mods: 'mods',
     modpacks: 'modpacks',
     settings: 'settings',
    },
   },
  },
  months: {
   jan: 'Jan',
   january: 'January',
   feb: 'Feb',
   february: 'February',
   mar: 'Mar',
   march: 'March',
   apr: 'Apr',
   april: 'April',
   may_: 'May',
   // longer
   may: 'May',
   jun: 'Jun',
   june: 'June',
   jul: 'Jul',
   july: 'July',
   aug: 'Aug',
   august: 'August',
   sep: 'Sep',
   september: 'September',
   oct: 'Oct',
   october: 'October',
   nov: 'Nov',
   november: 'November',
   dec: 'Dec',
   december: 'December',
  },
 },
 database: {
  titles: {
   contributions: 'Beiträge',
   contributors: 'Beitragende',
   textures: 'Texturen',
   users: 'Users',
   packs: 'Packs',
   add_user: 'Neuen Mitwirkenden hinzufügen',
   add_textures: 'Neue Texturen hinzufügen',
   add_texture: 'Neue Textur hinzufügen',
   add_pack: 'Add new pack',
   change_pack: 'Edit pack',
   add_submission: 'Add submission information',
   edit_submission: 'Edit submission information',
   add_use: 'Neue Verwendung hinzufügen',
   add_path: 'Neuen Dateipfad hinzufügen',
   add_mc_version: 'Neue Minecraft-Version hinzufügen',
   change_path: 'Dateipfad bearbeiten',
   change_use: 'Verwendung bearbeiten',
   change_texture: 'Textur bearbeiten',
   change_user: 'Mitwirkende bearbeiten',
   change_mc_version: 'Eine Minecraft-Version ändern',
   confirm_deletion: 'Löschung bestätigen',
  },
  subtitles: {
   add_manually: 'Manuell hinzufügen',
   add_new_contribution: 'Add a new contribution',
   clone_contribution: 'Clone the contribution',
   no_contributor_yet: 'No contributor yet',
   pack: 'Resource Pack',
   submissions: 'Submission information',
   github: 'GitHub',
   resource_packs: 'Filter by pack',
   channels: 'Discord channels',
   user: 'Mitwirkende/r',
   select_user_role: 'Mitwirkende/r-Typ auswählen',
   search: 'Suchen',
   texture_result: 'Texturergebnisse',
   pack_result: 'Pack results',
   user_result: 'User results',
   contribution_result: 'Contribution results',
   import_json_data: 'JSON-Daten importieren',
   uses: 'Verwendung(en)',
   paths: 'Dateipfad(e)',
  },
  labels: {
   copy_json_data: 'Copied JSON data to clipboard',
   anonymous: 'Anonymous',
   anonymous_explain:
    'If checked, the user\'s name will be displayed as "Anonymous" and their skin won\'t show up. Can only be changed by managers!',
   mcmeta: 'Animated',
   new_mc_version_edition: 'Edition, zu der die Version hinzugefügt werden soll',
   new_mc_version_path: 'Pfadversion, zu der die Version hinzugefügt werden soll',
   new_mc_version_name: 'Neuer Versionsname',
   nameless: 'Namenlos',
   tagless: 'No tags added',
   add_textures_success: 'Texturen erfolgreich hinzugefügt',
   add_version_success: 'Version erfolgreich hinzugefügt',
   add_new_user: 'Neuen Mitwirkenden hinzufügen',
   add_new_pack: 'Add new pack',
   add_new_texture: 'Neue Textur hinzufügen',
   add_new_path: 'Neuen Pfad hinzufügen',
   add_new_use: 'Neue Verwendung hinzufügen',
   add_edition_use: 'Add automatic %edition% use',
   add_texture: 'Texturen hinzufügen',
   add_mc_version: 'Neue Minecraft-Version hinzufügen',
   ask_deletion: 'Willst du %s (%d) löschen?',
   ask_submission_deletion: 'Do you want to delete submission information for %s (%d)?',
   close_on_submit: 'Close on submit',
   clear_on_save: 'Clear on save',
   user_role: 'Art des Mitwirkenden',
   discord_id: 'Discord-ID',
   pack_id: 'Pack ID',
   pack_name: 'Pack name',
   pack_tags: 'Pack tags',
   pack_resolution: 'Pack resolution',
   pack_logo: 'Pack logo URL',
   council_enabled: 'Enable council',
   contributor_role: 'Contributor role ID',
   time_to_results: 'Time to results',
   time_to_council: 'Time to council',
   channels: {
    submit: 'Submission channel',
    council: 'Council channel',
    results: 'Results channel',
   },
   github_org: 'Organization',
   github_repo: 'Repository',
   submission_reference: 'Reference pack',
   edit_submission: 'Edit submission information',
   invalid_url: 'This URL is not valid',
   new_submission: 'Enable submissions',
   edit_mc_version: 'Eine Minecraft-Version ändern',
   one_contributor: 'Bitte wähle mindestens einen Mitwirkenden',
   select_user: 'Select user(s)',
   parse_json: 'JSON in Daten umwandeln',
   search_contributions: 'Beiträge suchen',
   search_username: 'Benutzernamen suchen',
   search_texture: 'Texturname suchen',
   search_pack: 'Search packs',
   select_texture_tag: 'Texturtyp auswählen',
   select_pack_tag: 'Filter by tag',
   username: 'Benutzername',
   uuid: 'Minecraft Profil UUID',
   texture_name: 'Texturname',
   texture_tags: 'Textur-Typ',
   texture_id: 'Textur-ID',
   texture_uses: 'Textur-Verwendung(en)',
   use_name: 'Verwendungsname',
   use_id: 'Verwendungs-ID',
   use_edition: 'Verwendungsedition',
   path: 'Dateipfad',
   path_id: 'Dateipfad-ID',
   versions: 'Versionen',
   no_path_found: 'Keine Dateipfade für diese Verwendung gefunden.',
   no_use_found: 'Keine Verwendungen für diese Textur gefunden.',
   current_mc_version: 'Aktuelle MC-Version',
   new_mc_version: 'Neue MC-Version',
   id_field_errors: {
    one_required: 'At least one texture ID or an ID range is required',
    incorrect_value: 'Incorrect texture %value% ID or ID range',
   },
   use_singular: 'Use',
   use_plural: 'Uses',
   path_singular: 'Path',
   path_plural: 'Paths',
  },
  hints: {
   pack_id_creation: 'A Pack ID can either be manually specified or automatically generated.',
   pack_id_editing: 'Changing a pack ID can break everything!',
   pack_reference: 'Pack to compare against in submission embeds.',
   submission_timings: 'Delays are measured in days.',
   github_required: "An edition can be left blank if it's not yet supported.",
   channel_ids: 'Enable Developer Mode and right click on a channel to get channel IDs.',
   texture_id: 'Das Ändern der Textur-ID kann alles kaputt machen',
   use_id: 'Das Ändern der Verwendungs-ID kann alles kaputt machen',
   path_id: 'Das Ändern der Dateipfad-ID kann alles kaputt machen',
   path_prefill: 'Enter this first to generate most fields!',
   path: 'Der Dateipfad sollte mit dem Stammverzeichnis beginnen (Bsp.: assets/…)',
   example_scenario:
    'Ändert alle Instanzen einer Minecraft-Version in der Datenbank in eine andere Version. (Bsp. 1.17 → 1.17.1)',
   example_scenario_warn: 'Bitte vergesse nicht, auch die Namen aller GitHub-Branches zu aktualisieren!',
  },
  messages: {
   deleting_use_will_delete_paths: 'Deleting the use will also delete all its paths.',
  },
 },
 review: {
  titles: {
   addons: 'Add-ons überprüfen',
   translation: 'Übersetzungen überprüfen',
   pending: 'Genehmigung ausstehend',
   denied: 'Abgelehnt',
   approved: 'Genehmigt',
   archived: 'Archived',
  },
  deny_window: {
   title: 'Deny add-on',
   label: 'Schreibe einen Grund…',
   rule: 'Ein beliebiger Grund kann angegeben werden',
  },
  labels: {
   pending: 'Es gibt derzeit keine ausstehenden Add-ons!',
   denied: 'Es gibt derzeit keine abgelehnten Add-ons!',
   archived: 'There are currently no archived add-ons!',
   approved: 'There are current no approved add-ons!',
   load_approved: 'Genehmigte Add-ons laden',
  },
  addon: {
   titles: {
    authors: 'Autor(en)',
    description: 'Beschreibung',
    links: 'Links',
    options: 'Optionen',
   },
   labels: {
    link: 'Link',
    optifine: 'OptiFine',
    approved_by: 'Genehmigt von',
    denied_by: 'Abgelehnt von',
    reason: 'Grund',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Ein neues Add-on einreichen',
   edit: 'Edit add-on',
   submissions: 'Einreichungen',
   details: 'Details',
  },
  remove: {
   title: 'Löschung bestätigen',
   labels: {
    question: 'Willst du %s löschen?',
    warning: 'Du kannst diesen Vorgang nicht rückgängig machen.',
   },
  },
  general: {
   loading_addon: 'Loading add-on',
   rules: 'Make sure to read the add-on rules before submitting',
   title: 'Allgemein',
   name: {
    label: 'Add-on name',
    hint: 'A shorter name is preferred.',
    rules: {
     name_required: 'A name is required.',
     name_too_big: 'Add-on name must be less than %s characters.',
     name_too_small: 'Add-on name must be at least %s characters long.',
     name_unavailable: 'This name is already taken!',
    },
   },
   description: {
    label: 'Add-on Beschreibung',
    hint: 'Du kannst die Markdown-Formatierung verwenden, um deine Beschreibung zu verbessern!',
    rules: {
     description_required: 'Die Beschreibung ist erforderlich.',
     description_too_big: 'Die Beschreibung muss weniger als %s Zeichen enthalten.',
     description_too_small: 'Description must be at least %s characters long.',
    },
   },
   embed_description: {
    label: 'Embed description',
    hint: 'Description seen when sharing the add-on on social media',
    rules: {
     too_big: 'Embed description must be less than %s characters.',
    },
   },
   slug: {
    label: 'Add-on slug',
    hint: 'Changing this will break old links!',
   },
   reason: {
    title: 'Update reason',
    text: 'Please tell us what you updated to make reviewing your add-on easier!',
    required: 'An update reason is required',
    bounds: 'Update reason must be between %s and %s characters long',
   },
   authors: {
    label: 'Autoren für das Add-on auswählen',
    hint:
     'Jeder Autor kann das Add-on ändern, sobald es eingereicht wurde! | Wenn du in der Liste niemanden finden kannst, der dort sein sollte, kontaktiere einen Administrator/Entwickler.',
   },
  },
  images: {
   title: 'Screenshots',
   header: {
    labels: {
     drop: 'Klicken Sie, um zusätzliche Bilder auszuwählen',
     normal: 'Header-Bild',
     replace: 'Header-Bild ersetzen',
    },
    rules: {
     image_size: 'Die Bild sollte weniger als %s KB groß sein! Benutze https://compressor.io/ es zu komprimieren.',
     image_ratio: 'Falsches Seitenverhältnis: Das bereitgestellte Bild hat nicht das Seitenverhältnis 16:9.',
     image_required: 'Ein Header-Bild ist erforderlich.',
     jpeg: 'Image must be a lossy JPEG.',
    },
   },
   carousel: {
    labels: {
     drop: 'Klicken Sie, um zusätzliche Bilder auszuwählen',
     normal: 'Zusätzliche(s) Bild(er)',
     replace: 'Zusätzliche(s) Bild(er) ersetzen',
    },
    rule: 'Falsches Seitenverhältnis: Bilder ohne einem Seitenverhältnis von 16:9 wurden entfernt.',
   },
  },
  options: {
   title: 'Optionen',
   optifine: {
    label: 'Benötigt OptiFine',
   },
   editions: {
    label: 'Unterstützte Edition(en)',
    rule: 'Du musst mindestens eine Edition auswählen.',
   },
   resolutions: {
    label: 'Unterstützte Auflösung(en)',
    rule: 'Du musst mindestens eine Auflösung auswählen.',
   },
  },
  downloads: {
   title: 'Downloads',
   name: {
    placeholder: 'CurseForge, GitHub…',
    label: 'Name',
    rules: {
     name_required: 'Ein Name ist erforderlich.',
     name_cannot_be_empty: 'Name kann nicht leer sein.',
    },
   },
   link: {
    placeholder: 'https://www.beispiel.de/',
    label: 'Link',
    rule: 'Die URL muss gültig sein.',
   },
  },
  status: {
   approved: 'Genehmigt',
   denied: 'Abgelehnt',
   pending: 'Ausstehend',
  },
 },
 posts: {
  titles: {
   list: 'All posts',
   edit: 'Edit post',
   new: 'Create new post',
  },
  status: {
   published: 'Published',
   pending: 'Pending',
  },
  loading: 'Loading post…',
  general: {
   heading: 'General',
   title: {
    label: 'Post title',
    placeholder: 'Faithful Smart Fridge – Alpha 1',
   },
   permalink: {
    label: 'Permalink',
    placeholder: '/faithfulsmartfridge/A1',
   },
   header_img: {
    label: 'Header image (optional)',
    hint: 'Note: This must be uploaded separately',
    placeholder: 'https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Post release date',
    placeholder: 'YYYY-MM-DD',
   },
   description: {
    label: 'Post description',
    hint: 'You can use HTML markup to improve your description!',
   },
  },
  download: {
   heading: 'Downloads',
   add_category: 'Add download category',
   add_single_item: 'Add single download',
   category: 'Download category name',
   name: 'Download name',
   link: 'Download link',
   link_placeholder: 'https://www.example.com/',
  },
  changelog: {
   heading: 'Changelog',
   add_category: 'Add changelog category',
   add_item: 'Add changelog item',
   form_levels: {
    primary: 'Primary category',
    secondary: 'Secondary category',
    item_category: 'Item category (Authors)',
    item: 'Item (Authors)',
   },
  },
 },
 statistics: {
  title: 'Beitragsstatistik',
  loading: 'Loading graph…',
  label: {
   textures: 'Texturen',
   contributors: 'Mitwirkende',
   contributions: 'Beiträge',
  },
 },
 profile: {
  title: 'Profil',
  general: {
   title: 'Allgemein',
   uuid: {
    label: 'Minecraft-Profil UUID',
    hint: 'Your skin will be displayed with add-ons you authored.',
   },
   username: {
    label: 'Benutzername',
    hint: 'Dein Benutzername wird auf der Website angezeigt und für Beiträge, Add-ons usw. verwendet.',
   },
  },
  social: {
   title: 'Soziale Links',
   link_label: 'Edit link',
   type_label: 'Select media type',
   placeholder: 'https://www.beispiel.de/',
   add: 'Add social media',
  },
  save_changes: 'Save changes',
  delete: {
   title: 'Delete account',
   btn: 'Delete account',
   description: 'Are you sure you want to delete your account?',
   warning: 'This process is irreversible!',
  },
 },
 files: {
  general: {
   name: {
    label: 'File name',
    hint: 'Name describes shortly the file',
    rules: {
     name_required: 'A name is required.',
     name_too_big: 'File name must be less than %s characters.',
     name_too_small: 'File name must be at least %s characters long.',
    },
   },
   use: {
    label: 'File use',
    hint: 'Describes short use',
    rules: {
     name_required: 'A value is required.',
     name_too_big: 'File use must be less than %s characters.',
     name_too_small: 'File use must be at least %s characters long.',
    },
   },
  },
 },
 gallery: {
  stretched_switcher: 'Full width view',
  share_link_copied_to_clipboard: 'Share link copied to clipboard',
  max_items_per_row: 'Max items per row',
  title: 'Gallery',
  loading_message: 'Loading…',
  error_message: {
   texture_not_done: 'This texture is missing!',
   user_anonymous: 'Anonymous',
   user_not_found: 'Unknown User',
   contribution_not_found: 'No contributions found in database!',
  },
  category: {
   search: 'Search',
   tag: 'Tag',
   mc_version: 'Minecraft Version',
   edition: 'Edition',
   pack: 'Pack',
  },
  sort: {
   name_asc: 'Name (A → Z)',
   name_desc: 'Name (Z → A)',
   id_asc: 'Texture ID (smallest → largest)',
   id_desc: 'Texture ID (largest → smallest)',
   contrib_desc: 'Recently Contributed',
  },
  tooltip: {
   modded: 'Modded Texture',
   mojang: 'Mojang Studios',
   ignored: 'Ignored Texture',
  },
  all: 'All',
  latest: 'Latest',
  clear_cache: 'Clear Gallery Cache',
  result_stats_singular: '%COUNT% texture found in %SECONDS% seconds',
  result_stats_plural: '%COUNT% textures found in %SECONDS% seconds',
  modal: {
   no_contributions: 'No contributions found',
   tabs: {
    information: 'information',
    authors: 'authors',
   },
   info: {
    texture: 'Texture',
    uses: 'Uses',
    paths: 'Paths',
   },
   data: {
    contribution_id: 'Contribution ID',
    date: 'Date',
    authors: 'Authors',
    id: 'ID',
    name: 'Name',
    tags: 'Tags',
    use_id: 'Use ID',
    use_name: 'Use name',
    edition: 'Edition',
    texture_id: 'Texture ID',
    path_id: 'Path ID',
    resource_pack_path: 'Resource pack path',
    mc_versions: 'Minecraft versions',
   },
  },
 },
 settings: {
  title: 'Settings',
  label: {
   edit_raw: 'Edit raw JSON',
   edit_editor: 'Edit with visual editor',
  },
 },
 dashboard: {
  welcome_user: 'Welcome %USER%!',
  welcome: 'Welcome!',
  totals: {
   authors: 'authors',
   contributions: 'contributions',
   last_day: 'contributions in the last 48 hours',
   last_week: 'contributions last week',
   last_month: 'contributions last month',
  },
  titles: {
   users: 'Users',
   addons: 'Add-ons',
   contribution_activity: 'Contribution Activity',
   contribution_stats: 'Contributions',
   profile: 'Profile',
  },
  addons: {
   submissions: 'Submissions',
   upload: 'Upload',
  },
  users: {
   total: 'users',
   total_anonymous: 'anonymous',
   total_roles: 'roles',
  },
  locale: {
   on: 'on',
   less: 'Less',
   more: 'More',
  },
 },
 missing_page: {
  title: 'Are you lost in The End?',
  description: "Unfortunately, the page you requested doesn't exist!",
  main_page: 'Try checking your spelling or going to the %main page% to find what you were looking for.',
 },
 datepicker: {
  year: 'Year',
  month: 'Month',
  day: 'Day',
 },
};
