/**
 * This file is the template for all other languages
 */

export default {
 global: {
  name: 'Aplicación Web Faithful',
  logout: 'Cerrar Sesión',
  login: 'Iniciar sesión mediante Discord',
  ends_success: 'Completado con éxito',
  loading: 'Cargando, por favor espere…',
  no_results: 'No se han encontrado resultados',
  nyi: 'Aún no implementado.',
  translations: 'Traducciones',
  snackbar_system_theme: {
   sentence: 'El tema del sistema ha cambiado a %s',
   themes: {
    title: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
   },
  },
  btn: {
   add: 'Agregar',
   add_download: 'Agregar Descarga',
   submit: 'Enviar',
   submit_and_approve: 'Enviar y confirmar',
   cancel: 'Cancelar',
   close: 'Cerrar',
   save: 'Guardar',
   edit: 'Editar',
   delete: 'Eliminar',
   ok: 'Ok',
   yes: 'Sí',
   deny: 'Rechazar',
   approve: 'Confirmar',
   archive: 'Archivar',
   load_more: 'Cargar más',
   discard: 'Descartar',
   confirm: 'Confirmar',
   publish: 'Publicar',
   save_draft: 'Guardar como borrador',
  },
  tabs: {
   general: {
    title: 'general',
    subtabs: {
     dashboard: 'panel de control',
     profile: 'perfil',
     statistics: 'estadísticas',
     gallery: 'galería',
    },
   },
   addons: {
    title: 'complementos',
    subtabs: {
     submissions: 'envíos',
     upload: 'subir',
    },
   },
   review: {
    title: 'comentarios',
    subtabs: {
     addons: 'complementos',
     translations: 'traducciones',
    },
   },
   posts: {
    title: 'publicaciones',
    subtabs: {
     list: 'lista',
     create: 'crear',
    },
   },
   database: {
    title: 'base de datos',
    subtabs: {
     contributions: 'contribuciones',
     users: 'usuarios',
     textures: 'texturas',
     packs: 'packs',
     files: 'archivos',
     mods: 'mods',
     modpacks: 'modpacks',
     settings: 'ajustes',
    },
   },
  },
  months: {
   jan: 'Ene',
   january: 'Enero',
   feb: 'Feb',
   february: 'Febrero',
   mar: 'Mar',
   march: 'Marzo',
   apr: 'Abr',
   april: 'Abril',
   may_: 'May',
   // longer
   may: 'Mayo',
   jun: 'Jun',
   june: 'Junio',
   jul: 'Jul',
   july: 'Julio',
   aug: 'Ago',
   august: 'Agosto',
   sep: 'Set',
   september: 'Setiembre',
   oct: 'Oct',
   october: 'Octubre',
   nov: 'Nov',
   november: 'Noviembre',
   dec: 'Dic',
   december: 'Diciembre',
  },
 },
 database: {
  titles: {
   contributions: 'Contribuciones',
   contributors: 'Contribuidores',
   textures: 'Texturas',
   users: 'Usuarios',
   packs: 'Packs',
   add_user: 'Agregar nuevo usuario',
   add_textures: 'Agregar nuevas texturas',
   add_texture: 'Agregar nueva textura',
   add_pack: 'Agregar nuevo pack',
   change_pack: 'Editar pack',
   add_submission: 'Agregar información de envío',
   edit_submission: 'Editar información de envío',
   add_use: 'Agregar nuevo uso',
   add_path: 'Agregar nueva ruta',
   add_mc_version: 'Agregar nueva versión de Minecraft',
   change_path: 'Editar ruta',
   change_use: 'Editar uso',
   change_texture: 'Editar textura',
   change_user: 'Editar usuario',
   change_mc_version: 'Modificar una versión de Minecraft',
   confirm_deletion: 'Confirmar eliminación',
  },
  subtitles: {
   add_manually: 'Agregar manualmente',
   add_new_contribution: 'Agregar una nueva contribución',
   clone_contribution: 'Clonar la contribución',
   no_contributor_yet: 'Aún no hay contribuyentes',
   pack: 'Resource Pack',
   submissions: 'Información de envío',
   github: 'GitHub',
   resource_packs: 'Filtrar por pack',
   channels: 'Canales de Discord',
   user: 'Usuario',
   select_user_role: 'Filtrar por rol',
   search: 'Buscar',
   texture_result: 'Resultados de la textura',
   pack_result: 'Resultados del pack',
   user_result: 'Resultados del usuario',
   contribution_result: 'Resultados de la contribución',
   import_json_data: 'Importar datos JSON',
   uses: 'Usos',
   paths: 'Rutas',
  },
  labels: {
   copy_json_data: 'Datos JSON copiados en el portapapeles',
   anonymous: 'Anónimo',
   anonymous_explain:
    'Si está marcado, el nombre del usuario se mostrará como "Anónimo" y su aspecto no aparecerá. ¡Sólo puede ser cambiado por los administradores!',
   mcmeta: 'Animado',
   new_mc_version_edition: 'Nueva edición de versión',
   new_mc_version_path: 'Clonar una versión existente como una plantilla',
   new_mc_version_name: 'Nombre de la nueva versión',
   nameless: 'Sin Nombre',
   tagless: 'Sin etiquetas añadidas',
   add_textures_success: 'Textura(s) agregadas con éxito',
   add_version_success: 'Versión agregada correctamente',
   add_new_user: 'Agregar nuevo usuario',
   add_new_pack: 'Agregar nuevo pack',
   add_new_texture: 'Agregar nueva textura',
   add_new_path: 'Agregar nueva ruta',
   add_new_use: 'Agregar nuevo uso',
   add_edition_use: 'Agregar uso automático de %edition%',
   add_texture: 'Agregar nuevas texturas',
   add_mc_version: 'Agregar nueva versión de Minecraft',
   ask_deletion: '¿Desea eliminar %s (%d)?',
   ask_submission_deletion: '¿Desea eliminar la información de envío para %s (%d)?',
   close_on_submit: 'Cerrar al enviar',
   clear_on_save: 'Eliminar al guardar',
   user_role: 'Roles de usuario',
   discord_id: 'ID de Discord',
   pack_id: 'ID del pack',
   pack_name: 'Nombre del pack',
   pack_tags: 'Etiquetas del pack',
   pack_resolution: 'Resolución del pack',
   pack_logo: 'URL del logo del pack',
   council_enabled: 'Habilitar Consejo',
   contributor_role: 'ID de rol de contribuyente',
   time_to_results: 'Tiempo hasta los resultados',
   time_to_council: 'Hora del Consejo',
   channels: {
    submit: 'Canal de envío',
    council: 'Canal del Consejo',
    results: 'Canal de resultados',
   },
   github_org: 'Organización',
   github_repo: 'Repositorio',
   submission_reference: 'Pack de referencia',
   edit_submission: 'Editar información de envío',
   invalid_url: 'Esta URL no es válida',
   new_submission: 'Habilitar envíos',
   edit_mc_version: 'Modificar una versión de Minecraft',
   one_contributor: 'Seleccione al menos un contribuyente',
   select_user: 'Seleccionar usuario(s)',
   parse_json: 'Analizar JSON a datos',
   search_contributions: 'Buscar contribuciones',
   search_username: 'Buscar nombre de usuario',
   search_texture: 'Buscar el nombre de la textura',
   search_pack: 'Buscar packs',
   select_texture_tag: 'Filtrar por etiqueta',
   select_pack_tag: 'Filtrar por etiqueta',
   username: 'Nombre de usuario',
   uuid: 'UUID del perfil de Minecraft',
   texture_name: 'Nombre de la textura',
   texture_tags: 'Etiquetas de textura',
   texture_id: 'ID de textura',
   texture_uses: 'Usos de textura',
   use_name: 'Nombre de uso',
   use_id: 'ID de uso',
   use_edition: 'Edición de uso',
   path: 'Ruta',
   path_id: 'ID de Ruta',
   versions: 'Versiones',
   no_path_found: 'No se han encontrado rutas para este uso.',
   no_use_found: 'No se encontraron usos para esta textura.',
   current_mc_version: 'Versión actual de MC',
   new_mc_version: 'Nueva versión de MC',
   id_field_errors: {
    one_required: 'Se requiere al menos un ID de textura o un rango de ID',
    incorrect_value: 'Textura incorrecta %value% ID o rango de ID',
   },
   use_singular: 'Uso',
   use_plural: 'Usos',
   path_singular: 'Ruta',
   path_plural: 'Rutas',
  },
  hints: {
   pack_id_creation: 'Un ID de pack puede especificarse manualmente o generarse automáticamente.',
   pack_id_editing: '¡Cambiar un ID de pack puede romper todo!',
   pack_reference: 'Pack para comparar en las incrustaciones de envíos.',
   submission_timings: 'Las demoras se miden en días.',
   github_required: 'Una edición puede dejarse en blanco si aún no está soportada.',
   channel_ids: 'Habilita el Modo Desarrollador y haz clic derecho en un canal para obtener IDs de canal.',
   texture_id: '¡Cambiar un ID de pack puede romper todo!',
   use_id: '¡Cambiar un ID de pack puede romper todo!',
   path_id: '¡Cambiar un ID de pack puede romper todo!',
   path_prefill: '¡Ingrese esto primero para generar la mayoría de campos!',
   path: 'La ruta debe comenzar desde el directorio raíz (ej: assets/…)',
   example_scenario:
    'Cambia todas las instancias de una versión de Minecraft en la base de datos a una diferente. (ej. 1.17 → 1.17.1)',
   example_scenario_warn: '¡Por favor, no olvides actualizar todos los nombres de las rama de GitHub también!',
  },
  messages: {
   deleting_use_will_delete_paths: 'Eliminar el uso también eliminará todas sus rutas.',
  },
 },
 review: {
  titles: {
   addons: 'Revisar complementos',
   translation: 'Revisar traducciones',
   pending: 'Aprobación pendiente',
   denied: 'Denegado',
   approved: 'Aprobado',
   archived: 'Archivado',
  },
  deny_window: {
   title: 'Rechazar complemento',
   label: 'Escribe un motivo…',
   rule: 'Cualquier razón puede ser dada',
  },
  labels: {
   pending: 'Actualmente no hay complementos pendientes!',
   denied: 'Actualmente no hay complementos denegados!',
   archived: 'Actualmente no hay complementos archivados!',
   approved: '¡Actualmente no hay complementos aprobados!',
   load_approved: 'Cargar complementos aprobados',
  },
  addon: {
   titles: {
    author_singular: 'Autor',
    author_plural: 'Autores',
    description: 'Descripción',
    links: 'Enlaces',
    options: 'Opciones',
   },
   labels: {
    link: 'Enlace',
    optifine: 'OptiFine',
    approved_by: 'Aprobado por',
    denied_by: 'Denegado por',
    reason: 'Motivo',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Enviar un nuevo complemento',
   edit: 'Editar complemento',
   submissions: 'Envíos de complementos',
   details: 'Detalles',
  },
  remove: {
   title: 'Confirmar eliminación',
   labels: {
    question: '¿Quieres eliminar %s?',
    warning: 'No puedes deshacer esta operación.',
   },
  },
  general: {
   loading_addon: 'Cargando complemento',
   rules: 'Asegúrate de leer las reglas del complemento antes de enviar',
   title: 'General',
   name: {
    label: 'Nombre del complemento',
    hint: 'Un nombre más corto es preferido.',
    rules: {
     name_required: 'Se requiere un nombre.',
     name_too_big: 'El nombre del complemento debe tener menos de %s caracteres.',
     name_too_small: 'El nombre del complemento debe tener al menos %s caracteres.',
     name_unavailable: '¡Ese nombre ya está en uso!',
    },
   },
   description: {
    label: 'Descripción del complemento',
    hint: '¡Puedes usar el formato Markdown para mejorar tu descripción!',
    rules: {
     description_required: 'La descripción es requerida.',
     description_too_big: 'La descripción debe tener menos de %s caracteres.',
     description_too_small: 'La descripción debe tener menos de %s caracteres.',
    },
   },
   embed_description: {
    label: 'Incrustar descripción',
    hint: 'Descripción visible al compartir las redes sociales del complemento',
    rules: {
     too_big: 'La descripción incrustada debe tener menos de %s caracteres.',
    },
   },
   slug: {
    label: 'Slug de complemento',
    hint: '¡Cambiar esto romperá los enlaces antiguos!',
   },
   reason: {
    title: 'Actualizar razón',
    text: '¡Por favor, cuéntanos lo que actualizaste para facilitar la revisión de tu complemento!',
    required: 'Se requiere una razón de actualización',
    bounds: 'La razón de la actualización debe tener entre %s y %s caracteres',
   },
   authors: {
    label: 'Seleccionar autores para el complemento',
    hint:
     '¡Cualquier autor puede modificar el complemento una vez que sea enviado! | Si no puedes encontrar a nadie en la lista, contacta con un administrador o desarrollador',
   },
  },
  images: {
   title: 'Capturas de pantalla',
   header: {
    labels: {
     drop: 'Arrastra y suelta la imagen del encabezado o haz clic para subir',
     normal: 'Imagen del encabezado',
     replace: 'Reemplazar imagen del encabezado',
    },
    rules: {
     image_size: '¡El tamaño de la imagen debe ser inferior a %s KB! Use https://compressor.io/ para comprimirla.',
     image_ratio: 'Ratio incorrecto: La imagen proporcionada no tiene una relación lateral 16:9.',
     image_required: 'Se requiere una imagen de encabezado.',
     jpeg: 'Imagen debe ser un JPEG con pérdida.',
    },
   },
   carousel: {
    labels: {
     drop: 'Arrastre o haga clic para seleccionar imágenes adicionales',
     normal: 'Imágenes adicional(es)',
     replace: 'Reemplazar imagen(es) adicionales',
    },
    rule: 'Ratio incorrecto: Todas las imágenes con una relación lateral que no sea 16:9 han sido eliminadas.',
   },
  },
  options: {
   title: 'Opciones',
   optifine: {
    label: 'Requiere OptiFine',
   },
   editions: {
    label: 'Edición(es) soportadas',
    rule: 'Debe seleccionar al menos 1 edición.',
   },
   resolutions: {
    label: 'Resolución(es) soportadas',
    rule: 'Debe seleccionar al menos 1 resolución.',
   },
  },
  downloads: {
   title: 'Descargas',
   name: {
    placeholder: 'CurseForge, GitHub…',
    label: 'Nombre',
    rules: {
     name_required: 'Se requiere un nombre.',
     name_cannot_be_empty: 'El nombre no puede estar vacío.',
    },
   },
   link: {
    placeholder: 'https://www.ejemplo.com',
    label: 'Enlace',
    rule: 'La URL debe ser válida.',
   },
  },
  status: {
   approved: 'Aprobado',
   denied: 'Denegado',
   pending: 'Pendiente',
  },
 },
 posts: {
  titles: {
   list: 'Todas las publicaciones',
   edit: 'Editar publicación',
   new: 'Crear nueva publicación',
  },
  status: {
   published: 'Publicado',
   pending: 'Pendiente',
  },
  loading: 'Cargando publicación…',
  general: {
   heading: 'General',
   title: {
    label: 'Título de la publicación',
    placeholder: 'Faithful Smart Fridge – Alfa 1',
   },
   permalink: {
    label: 'Enlace permanente',
    placeholder: '/faithfulsmartfridge/A1',
   },
   header_img: {
    label: 'Imagen de encabezado (opcional)',
    hint: 'Nota: Esto debe ser subido por separado',
    placeholder: 'https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Fecha de lanzamiento',
    placeholder: 'AAAA-MM-DD',
   },
   description: {
    label: 'Descripción del post',
    hint: '¡Puedes usar el marcado HTML para mejorar tu descripción!',
   },
  },
  download: {
   heading: 'Descargas',
   add_category: 'Agregar categoría de descarga',
   add_single_item: 'Agregar descarga única',
   category: 'Nombre de la categoría de descarga',
   name: 'Nombre de la Descarga',
   link: 'Enlace de descarga',
   link_placeholder: 'https://www.ejemplo.com',
  },
  changelog: {
   heading: 'Registro de cambios',
   add_category: 'Agregar categoría de registro de cambios',
   add_item: 'Agregar elemento de registro de cambios',
   form_levels: {
    primary: 'Categoría principal',
    secondary: 'Categoría secundaria',
    item_category: 'Categoría de artículo (autores)',
    item: 'Artículo (autores)',
   },
  },
 },
 statistics: {
  title: 'Estadísticas de la contribución',
  loading: 'Cargando gráfico…',
  label: {
   textures: 'Texturas',
   contributors: 'Contribuyentes',
   contributions: 'Contribuciones',
  },
 },
 profile: {
  title: 'Perfil',
  general: {
   title: 'General',
   uuid: {
    label: 'UUID del perfil de Minecraft',
    hint: 'Tu skin se mostrará con los complementos que hayas creado.',
   },
   username: {
    label: 'Nombre de usuario',
    hint: 'Tu nombre de usuario se mostrará en servicios de Faithful para contribuciones, complementos, etc.',
   },
  },
  social: {
   title: 'Enlaces a redes sociales',
   link_label: 'Editar enlace',
   type_label: 'Seleccionar tipo de medio',
   placeholder: 'https://www.ejemplo.com',
   add: 'Añadir redes sociales',
  },
  save_changes: 'Guardar los cambios',
  delete: {
   title: 'Eliminar cuenta',
   btn: 'Eliminar cuenta',
   description: '¿Estás seguro de que quieres eliminar tu cuenta?',
   warning: 'Este proceso es irreversible!',
  },
 },
 files: {
  general: {
   name: {
    label: 'Nombre del archivo',
    hint: 'El nombre describe en breve al archivo',
    rules: {
     name_required: 'Se requiere un nombre.',
     name_too_big: 'El nombre del archivo debe tener menos de %s caracteres.',
     name_too_small: 'El nombre del archivo debe tener al menos %s caracteres.',
    },
   },
   use: {
    label: 'Uso del archivo',
    hint: 'Describe el uso corto',
    rules: {
     name_required: 'Se requiere un valor.',
     name_too_big: 'El uso del archivo debe tener menos de %s caracteres.',
     name_too_small: 'El uso del archivo debe tener al menos %s caracteres.',
    },
   },
  },
 },
 gallery: {
  stretched_switcher: 'Vista de ancho completo',
  share_link_copied_to_clipboard: 'Enlace para compartir copiado al portapapeles',
  max_items_per_row: 'Máximo de artículos por fila',
  title: 'Galería',
  loading_message: 'Cargando…',
  error_message: {
   texture_not_done: '¡Falta esta textura!',
   user_anonymous: 'Anónimo',
   user_not_found: 'Usuario desconocido',
   contribution_not_found: '¡No se encontraron contribuciones en la base de datos!',
  },
  category: {
   search: 'Buscar',
   tag: 'Etiqueta',
   mc_version: 'Versión de Minecraft',
   edition: 'Edición',
   pack: 'Pack',
  },
  sort: {
   name_asc: 'Nombre (A → Z)',
   name_desc: 'Nombre (Z → A)',
   id_asc: 'ID de textura (menor → mayor)',
   id_desc: 'ID de textura (mayor → menor)',
   contrib_desc: 'Contribuido recientemente',
  },
  tooltip: {
   modded: 'Textura modificada',
   mojang: 'Mojang Studios',
   ignored: 'Textura Ignorada',
  },
  all: 'Todos',
  latest: 'Reciente',
  clear_cache: 'Borrar caché de Galería',
  result_stats_singular: 'Textura %COUNT% encontrada en %SECONDS% segundos',
  result_stats_plural: '%COUNT% texturas encontradas en %SECONDS% segundos',
  modal: {
   no_contributions: 'No se ha encontrado ninguna contribución',
   tabs: {
    information: 'información',
    authors: 'autores',
   },
   info: {
    texture: 'Textura',
    uses: 'Usos',
    paths: 'Rutas',
   },
   data: {
    contribution_id: 'ID de contribución',
    date: 'Fecha',
    authors: 'Autores',
    id: 'ID',
    name: 'Nombre',
    tags: 'Etiquetas',
    use_id: 'ID de uso',
    use_name: 'Nombre de uso',
    edition: 'Edición',
    texture_id: 'ID de textura',
    path_id: 'ID de Ruta',
    resource_pack_path: 'Ruta del Resource pack',
    mc_versions: 'Versiones de Minecraft',
   },
  },
 },
 settings: {
  title: 'Ajustes',
  label: {
   edit_raw: 'Editar JSON sin procesar',
   edit_editor: 'Editar con editor visual',
  },
 },
 dashboard: {
  welcome_user: '¡Bienvenido %USER%!',
  welcome: '¡Bienvenido!',
  totals: {
   authors: 'autores',
   contributions: 'contribuciones',
   last_day: 'contribuciones en las últimas 48 horas',
   last_week: 'contribuciones en la última semana',
   last_month: 'contribuciones en el último mes',
  },
  titles: {
   users: 'Usuarios',
   addons: 'Complementos',
   contribution_activity: 'Actividad de contribución',
   contribution_stats: 'Contribuciones',
   profile: 'Perfil',
  },
  addons: {
   submissions: 'Envíos',
   upload: 'Subir',
  },
  users: {
   total: 'usuarios',
   total_anonymous: 'anónimos',
   total_roles: 'roles',
  },
  locale: {
   on: 'en',
   less: 'Menos',
   more: 'Más',
  },
 },
 missing_page: {
  title: '¿Estás perdido en El End?',
  description: 'Desafortunadamente, la página solicitada no existe!',
  main_page: 'Intenta revisar tu ortografía o ir a la %main page% para encontrar lo que estabas buscando.',
 },
 datepicker: {
  year: 'Año',
  month: 'Mes',
  day: 'Día',
 },
};
