/**
 * This file is the template for all other languages
 */

export default {
 global: {
  name: 'Application Web Faithful',
  logout: 'Déconnexion',
  login: 'Se connecter via Discord',
  ends_success: 'Terminé avec succès',
  loading: 'Chargement, veuillez patienter…',
  no_results: "Aucun résultat n'a été trouvé",
  nyi: "N'a pas encore été implémenté.",
  translations: 'Traductions',
  snackbar_system_theme: {
   sentence: 'Thème système changé en %s',
   themes: {
    title: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
   },
  },
  btn: {
   add: 'Ajouter',
   add_download: 'Ajouter un lien',
   submit: 'Soumettre',
   submit_and_approve: 'Soumettre et approuver',
   cancel: 'Annuler',
   close: 'Fermer',
   save: 'Sauvegarder',
   edit: 'Éditer',
   delete: 'Supprimer',
   ok: 'OK',
   yes: 'Oui',
   deny: 'Refuser',
   approve: 'Approuver',
   archive: 'Archiver',
   load_more: 'Charger plus',
   discard: 'Discard',
   confirm: 'Confirm',
   publish: 'Publish',
   save_draft: 'Save as draft',
  },
  tabs: {
   general: {
    title: 'general',
    subtabs: {
     dashboard: 'dashboard',
     profile: 'profil',
     statistics: 'statistiques',
     gallery: 'galerie',
    },
   },
   addons: {
    title: 'add-on',
    subtabs: {
     submissions: 'mes add-ons',
     upload: 'upload',
    },
   },
   review: {
    title: 'vérification',
    subtabs: {
     addons: 'add-ons',
     translations: 'traductions',
    },
   },
   posts: {
    title: 'posts',
    subtabs: {
     list: 'list',
     create: 'create',
    },
   },
   database: {
    title: 'database',
    subtabs: {
     contributions: 'contributions',
     users: 'utilisateurs',
     textures: 'textures',
     packs: 'packs',
     files: 'fichiers',
     mods: 'mods',
     modpacks: 'modpacks',
     settings: 'Paramètres',
    },
   },
  },
  months: {
   jan: 'Jan',
   january: 'Janvier',
   feb: 'Fév',
   february: 'Février',
   mar: 'Mar',
   march: 'Mars',
   apr: 'Avr',
   april: 'Avril',
   may_: 'Mai',
   // longer
   may: 'Mai',
   jun: 'Juin',
   june: 'Juin',
   jul: 'Juil',
   july: 'Juillet',
   aug: 'Aoû',
   august: 'Août',
   sep: 'Sep',
   september: 'Septembre',
   oct: 'Oct',
   october: 'Octobre',
   nov: 'Nov',
   november: 'Novembre',
   dec: 'Déc',
   december: 'Décembre',
  },
 },
 database: {
  titles: {
   contributions: 'Contributions',
   contributors: 'Contributeurs',
   textures: 'Textures',
   users: 'Users',
   packs: 'Packs',
   add_user: 'Ajouter un contributeur',
   add_textures: 'Ajouter des textures',
   add_texture: 'Ajouter une texture',
   add_pack: 'Add new pack',
   change_pack: 'Edit pack',
   add_submission: 'Add submission information',
   edit_submission: 'Edit submission information',
   add_use: 'Ajouter une utilisation',
   add_path: 'Ajouter un chemin',
   add_mc_version: 'Ajouter une nouvelle version Minecraft',
   change_path: 'Éditer le chemin',
   change_use: "Éditer l'utilisation",
   change_texture: 'Éditer la texture',
   change_user: 'Éditer le contributeur',
   change_mc_version: 'Modifier une version de Minecraft',
   confirm_deletion: 'Confirmer la suppression',
  },
  subtitles: {
   add_manually: 'Ajouter manuellement',
   add_new_contribution: 'Ajouter une nouvelle contribution',
   clone_contribution: 'Cloner la contribution',
   no_contributor_yet: 'Pas encore de contributeurs',
   pack: 'Pack de Ressources',
   submissions: 'Submission information',
   github: 'GitHub',
   resource_packs: 'Filter by pack',
   channels: 'Discord channels',
   user: 'Utilisateurs',
   select_user_role: "Sélectionnez le role de l'utilisateur",
   search: 'Rechercher',
   texture_result: 'Résultats des textures',
   pack_result: 'Pack results',
   user_result: 'User results',
   contribution_result: 'Contribution results',
   import_json_data: 'Importer des données JSON',
   uses: 'Utilisation(s)',
   paths: 'Chemin(s)',
  },
  labels: {
   copy_json_data: 'Copied JSON data to clipboard',
   anonymous: 'Anonyme',
   anonymous_explain:
    'Si coché, l\'utilisateur sera renommé "Anonyme" et son skin ne sera pas affichée. Cela n\'est modifiable que par les administrateurs!',
   mcmeta: 'Animated',
   new_mc_version_edition: 'Édition à laquelle ajouter une version',
   new_mc_version_path: 'Version du chemin auquel ajouter la version',
   new_mc_version_name: 'Nom de la nouvelle version',
   nameless: 'Sans nom',
   tagless: 'No tags added',
   add_textures_success: 'Textures ajoutées avec succès',
   add_version_success: 'Version ajoutée avec succès',
   add_new_user: 'Ajouter un nouveau utilisateur',
   add_new_pack: 'Add new pack',
   add_new_texture: 'Ajouter une nouvelle texture',
   add_new_path: 'Ajouter un nouveau chemin',
   add_new_use: 'Ajouter une nouvelle utilisation',
   add_edition_use: 'Add automatic %edition% use',
   add_texture: 'Ajouter des textures',
   add_mc_version: 'Ajouter une nouvelle version Minecraft',
   ask_deletion: 'Voulez-vous supprimer %s (%d)?',
   ask_submission_deletion: 'Do you want to delete submission information for %s (%d)?',
   close_on_submit: "Fermer à l'envoi",
   clear_on_save: 'Clear on save',
   user_role: "Roles de l'utilisateur",
   discord_id: 'ID Discord',
   pack_id: 'Pack ID',
   pack_name: 'Pack name',
   pack_tags: 'Pack tags',
   pack_resolution: 'Pack resolution',
   pack_logo: 'Pack logo URL',
   council_enabled: 'Enable council',
   contributor_role: 'Contributor role ID',
   time_to_results: 'Time to results',
   time_to_council: 'Time to council',
   channels: {
    submit: 'Submission channel',
    council: 'Council channel',
    results: 'Results channel',
   },
   github_org: 'Organization',
   github_repo: 'Repository',
   submission_reference: 'Reference pack',
   edit_submission: 'Edit submission information',
   invalid_url: 'This URL is not valid',
   new_submission: 'Enable submissions',
   edit_mc_version: 'Modifier une version Minecraft',
   one_contributor: 'Veuillez choisir au moins un utilisateur',
   select_user: 'Select user(s)',
   parse_json: 'Analyser le JSON en données',
   search_contributions: 'Rechercher des contributions',
   search_username: 'Rechercher un pseudonyme',
   search_texture: 'Rechercher un nom de texture',
   search_pack: 'Search packs',
   select_texture_tag: 'Sélectionner un type de texture',
   select_pack_tag: 'Filter by tag',
   username: 'Pseudonyme',
   uuid: 'UUID du profil Minecraft',
   texture_name: 'Nom de la texture',
   texture_tags: 'Type de la texture',
   texture_id: 'ID de la texture',
   texture_uses: 'Utilisation(s) de la texture',
   use_name: "Nom de l'utilisation",
   use_id: "ID de l'utilisation",
   use_edition: "Edition de l'utilisation",
   path: 'Chemin',
   path_id: 'ID du chemin',
   versions: 'Versions',
   no_path_found: 'Aucun chemin trouvé pour cette utilisation',
   no_use_found: 'Aucune utilisation trouvée pour cette texture.',
   current_mc_version: 'Version MC actuelle',
   new_mc_version: 'Nouvelle version MC',
   id_field_errors: {
    one_required: "Au moins un ID ou une plage d'IDs de textures requis",
    incorrect_value: 'ID ou plage d\'IDs "%value%" incorrecte',
   },
   use_singular: 'Use',
   use_plural: 'Uses',
   path_singular: 'Path',
   path_plural: 'Paths',
  },
  hints: {
   pack_id_creation: 'A Pack ID can either be manually specified or automatically generated.',
   pack_id_editing: 'Changing a pack ID can break everything!',
   pack_reference: 'Pack to compare against in submission embeds.',
   submission_timings: 'Delays are measured in days.',
   github_required: "An edition can be left blank if it's not yet supported.",
   channel_ids: 'Enable Developer Mode and right click on a channel to get channel IDs.',
   texture_id: "Changer l'ID de la texture peut tout casser",
   use_id: "Changer l'ID de l'utilisation peut tout casser",
   path_id: "Changer l'ID du chemin peut tout casser",
   path_prefill: 'Enter this first to generate most fields!',
   path: 'Le chemin doit commencer à partir du répertoire racine (ex: assets/…)',
   example_scenario:
    'Hm, toute la base de donnée est configurée pour télécharger les textures pour la version 1.17 mais il existe désormais une version 1.17.1, cette option est faite pour vous !',
   example_scenario_warn: "N'oubliez pas de mettre également à jour toutes les branches GitHub !",
  },
  messages: {
   deleting_use_will_delete_paths: 'Deleting the use will also delete all its paths.',
  },
 },
 review: {
  titles: {
   addons: 'Vérifier les Add-ons',
   translation: 'Vérifier les traductions',
   pending: 'En attente de validation',
   denied: 'Refusé(s)',
   approved: 'Accepté(s)',
   archived: 'Archivé(s)',
  },
  deny_window: {
   title: 'Deny add-on',
   label: 'Écrivez une raison…',
   rule: 'Toute raison peut être donnée',
  },
  labels: {
   pending: "Il n'y a actuellement aucun add-on en attente !",
   denied: "Il n'y a actuellement aucun add-on refusé !",
   archived: "Il n'y a actuellement aucun add-on archivé !",
   approved: 'There are current no approved add-ons!',
   load_approved: 'Charger les add-on approuvés',
  },
  addon: {
   titles: {
    authors: 'Auteur(s)',
    description: 'Description',
    links: 'Liens',
    options: 'Options',
   },
   labels: {
    link: 'Lien',
    optifine: 'OptiFine',
    approved_by: 'Approuvé par',
    denied_by: 'Refusé par',
    reason: 'Raison',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Soumettre un nouvel Add-on',
   edit: "Éditer l'addon",
   submissions: 'Mes Add-ons',
   details: 'Details',
  },
  remove: {
   title: 'Confirmer la suppression',
   labels: {
    question: 'Voulez-vous vraiment supprimer %s?',
    warning: 'Vous ne pouvez pas revenir en arrière après cela.',
   },
  },
  general: {
   loading_addon: "Chargement de l'addon",
   rules: "Assurez-vous que l'add-on suit les règles décrites dans la documentation",
   title: 'Général',
   name: {
    label: "Nom de l'add-on",
    hint: 'Un nom court sera meilleur !',
    rules: {
     name_required: 'Le nom est requis.',
     name_too_big: 'Le nom doit faire moins que %s caractères.',
     name_too_small: 'Add-on name must be at least %s characters long.',
     name_unavailable: 'Ce nom est déjà pris !',
    },
   },
   description: {
    label: "Description de l'add-on",
    hint: 'Vous pouvez utilisez des balises Markdown pour améliorer votre description !',
    rules: {
     description_required: 'La description est requise.',
     description_too_big: 'La description ne doit pas dépasser %s caractères.',
     description_too_small: 'Description must be at least %s characters long.',
    },
   },
   embed_description: {
    label: 'Embed description',
    hint: 'Description seen when sharing the add-on on social media',
    rules: {
     too_big: 'Embed description must be less than %s characters.',
    },
   },
   slug: {
    label: 'Add-on slug',
    hint: 'Changing this will break old links!',
   },
   reason: {
    title: 'Update reason',
    text: 'Please tell us what you updated to make reviewing your add-on easier!',
    required: 'An update reason is required',
    bounds: 'Update reason must be between %s and %s characters long',
   },
   authors: {
    label: 'Sélectionner un ou des auteurs pour cet add-on',
    hint:
     "N'importe quel auteur peut modifier l'add-on une fois soumis ! | Si vous ne trouvez pas quelqu'un dans la liste, contactez un Administrateur/Développeur",
   },
  },
  images: {
   title: "Captures d'écran",
   header: {
    labels: {
     drop: "Glissez l'image d'en-tête ou cliquez pour sélectionner",
     normal: "Image d'en-tête",
     replace: "Changer l'image d'en-tête",
    },
    rules: {
     image_size: "L'image doit faire moins de %s KB! Utilisez https://compressor.io/ pour le compresser.",
     image_ratio: "Ratio incorrect: L'image envoyée ne possède pas un ratio en 16/9.",
     image_required: "Une image d'en-tête est requise.",
     jpeg: 'Image must be a lossy JPEG.',
    },
   },
   carousel: {
    labels: {
     drop: 'Glissez ou cliquez pour ajouter des images additionnelles',
     normal: 'Image(s) additionnelles',
     replace: 'Remplacer les images additionnelles',
    },
    rule: "Ratio incorrect: Les images qui n'ont pas un ratio en 16/9 ont été enlevées.",
   },
  },
  options: {
   title: 'Options',
   optifine: {
    label: 'Requière OptiFine',
   },
   editions: {
    label: 'Edition(s) supportées',
    rule: 'Vous devez choisir au moins 1 édition.',
   },
   resolutions: {
    label: 'Résolutions supportées',
    rule: 'Vous devez choisir au moins 1 résolution.',
   },
  },
  downloads: {
   title: 'Téléchargements',
   name: {
    placeholder: 'CurseForge, GitHub…',
    label: 'Nom',
    rules: {
     name_required: 'Un nom est requis.',
     name_cannot_be_empty: 'Le nom ne peut être vide.',
    },
   },
   link: {
    placeholder: 'https://www.exemple.com/',
    label: 'Lien',
    rule: "L'URL doit être valide.",
   },
  },
  status: {
   approved: 'Approuvé',
   denied: 'Refusé',
   pending: 'En attente',
  },
 },
 posts: {
  titles: {
   list: 'All posts',
   edit: 'Edit post',
   new: 'Create new post',
  },
  status: {
   published: 'Published',
   pending: 'En attente',
  },
  loading: 'Loading post…',
  general: {
   heading: 'Général',
   title: {
    label: 'Post title',
    placeholder: 'Faithful Smart Fridge – Alpha 1',
   },
   permalink: {
    label: 'Permalink',
    placeholder: '/faithfulsmartfridge/A1',
   },
   header_img: {
    label: 'Header image (optional)',
    hint: 'Note: This must be uploaded separately',
    placeholder: 'https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Post release date',
    placeholder: 'YYYY-MM-DD',
   },
   description: {
    label: 'Post description',
    hint: 'You can use HTML markup to improve your description!',
   },
  },
  download: {
   heading: 'Téléchargements',
   add_category: 'Add download category',
   add_single_item: 'Add single download',
   category: 'Download category name',
   name: 'Download name',
   link: 'Download link',
   link_placeholder: 'https://www.exemple.com/',
  },
  changelog: {
   heading: 'Changelog',
   add_category: 'Add changelog category',
   add_item: 'Add changelog item',
   form_levels: {
    primary: 'Primary category',
    secondary: 'Secondary category',
    item_category: 'Item category (Authors)',
    item: 'Item (Authors)',
   },
  },
 },
 statistics: {
  title: 'Statistiques des contributions',
  loading: 'Loading graph…',
  label: {
   textures: 'Textures',
   contributors: 'Contributeurs',
   contributions: 'Contributions',
  },
 },
 profile: {
  title: 'Profil',
  general: {
   title: 'Général',
   uuid: {
    label: 'UUID du profil Minecraft',
    hint: 'Your skin will be displayed with add-ons you authored.',
   },
   username: {
    label: 'Pseudonyme',
    hint:
     'Votre pseudonyme sera affiché et utilisé sur le site pour les contributions, les add-ons et bien plus encore…',
   },
  },
  social: {
   title: 'Réseaux Sociaux',
   link_label: 'Edit link',
   type_label: 'Select media type',
   placeholder: 'https://www.exemple.com/',
   add: 'Add social media',
  },
  save_changes: 'Save changes',
  delete: {
   title: 'Delete account',
   btn: 'Delete account',
   description: 'Are you sure you want to delete your account?',
   warning: 'This process is irreversible!',
  },
 },
 files: {
  general: {
   name: {
    label: 'Nom de fichier',
    hint: 'Décrit brièvement le fichier',
    rules: {
     name_required: 'Un nom est requis.',
     name_too_big: 'Le nom de fichier doit faire moins de %s caractères.',
     name_too_small: 'Le nom de fichier doit faire plus de %s caractères.',
    },
   },
   use: {
    label: 'Utilisation de fichier',
    hint: "Décrit l'utilisation brièvement",
    rules: {
     name_required: 'Une valeur est requise.',
     name_too_big: "L'utilisation du fichier doit faire moins de %s caractères.",
     name_too_small: "L'utilisation du fichier doit faire plus de %s caractères.",
    },
   },
  },
 },
 gallery: {
  stretched_switcher: 'Full width view',
  share_link_copied_to_clipboard: 'Share link copied to clipboard',
  max_items_per_row: "Maximum d'items par ligne",
  title: 'Galerie',
  loading_message: 'Chargement…',
  error_message: {
   texture_not_done: "La texture n'a pas été faite !",
   user_anonymous: 'Anonyme',
   user_not_found: 'Utilisateur Inconnu',
   contribution_not_found: 'Aucune contribution trouvée dans la base de donnée!',
  },
  category: {
   search: 'Rechercher',
   tag: 'Tag',
   mc_version: 'Versions Minecraft',
   edition: 'Édition',
   pack: 'Pack',
  },
  sort: {
   name_asc: 'Name (A → Z)',
   name_desc: 'Name (Z → A)',
   id_asc: 'Texture ID (smallest → largest)',
   id_desc: 'Texture ID (largest → smallest)',
   contrib_desc: 'Recently Contributed',
  },
  tooltip: {
   modded: 'Modded Texture',
   mojang: 'Mojang Studios',
   ignored: 'Ignored Texture',
  },
  all: 'Tout',
  latest: 'Latest',
  clear_cache: 'Clear Gallery Cache',
  result_stats_singular: '%COUNT% texture found in %SECONDS% seconds',
  result_stats_plural: '%COUNT% textures found in %SECONDS% seconds',
  modal: {
   no_contributions: 'No contributions found',
   tabs: {
    information: 'information',
    authors: 'auteurs',
   },
   info: {
    texture: 'Texture',
    uses: 'Utilisations',
    paths: 'Chemins',
   },
   data: {
    contribution_id: 'Contribution ID',
    date: 'Date',
    authors: 'Auteur(s)',
    id: 'ID',
    name: 'Nom',
    tags: 'Tags',
    use_id: "ID de l'utilisation",
    use_name: "Nom de l'utilisation",
    edition: 'Édition',
    texture_id: 'ID de la texture',
    path_id: 'ID du chemin',
    resource_pack_path: 'Chemin dans le Resource Pack',
    mc_versions: 'Version(s) Minecraft',
   },
  },
 },
 settings: {
  title: 'Settings',
  label: {
   edit_raw: 'Éditer le JSON',
   edit_editor: "Éditer avec l'éditeur visuel",
  },
 },
 dashboard: {
  welcome_user: 'Bienvenue %USER% !',
  welcome: 'Bienvenue !',
  totals: {
   authors: 'auteurs',
   contributions: 'contributions',
   last_day: 'contributions dans les 48 dernières heures',
   last_week: 'contributions cette semaine',
   last_month: 'contributions ce mois',
  },
  titles: {
   users: 'Users',
   addons: 'Add-ons',
   contribution_activity: 'Contribution Activity',
   contribution_stats: 'Contributions',
   profile: 'Profil',
  },
  addons: {
   submissions: 'Submissions',
   upload: 'Upload',
  },
  users: {
   total: 'utilisateurs',
   total_anonymous: 'anonymes',
   total_roles: 'roles',
  },
  locale: {
   on: 'le',
   less: 'Moins',
   more: 'Plus',
  },
 },
 missing_page: {
  title: 'Are you lost in The End?',
  description: "Unfortunately, the page you requested doesn't exist!",
  main_page: 'Try checking your spelling or going to the %main page% to find what you were looking for.',
 },
 datepicker: {
  year: 'Année',
  month: 'Mois',
  day: 'Jour',
 },
};
