export default {
	credits: ["pure_shadow."],
	global: {
		name: "Aplicativo Web Faithful",
		logout: "Sair",
		login: "Entrar com Discord",
		ends_success: "Concluído com sucesso",
		loading: "Carregando, por favor aguarde…",
		no_results: "Nenhum resultado encontrado",
		nyi: "Não implementado ainda.",
		invalid_url: "Esta URL não é válida",
		translations: "Traduções",
		snackbar_system_theme: {
			sentence: "Tema do sistema alterado para %s",
			themes: {
				title: "Tema",
				light: "Claro",
				dark: "Escuro",
				system: "Sistema",
			},
		},
		btn: {
			add: "Adicionar",
			add_download: "Adicionar download",
			submit: "Enviar",
			submit_for_review: "Enviar para revisão",
			submit_and_approve: "Enviar e aprovar",
			cancel: "Cancelar",
			close: "Fechar",
			save: "Salvar",
			edit: "Editar",
			delete: "Excluir",
			ok: "OK",
			yes: "Sim",
			deny: "Negar",
			approve: "Aprovar",
			archive: "Arquivar",
			load_more: "Carregar mais",
			discard: "Descartar",
			confirm: "Confirmar",
			publish: "Publicar",
			save_draft: "Salvar como rascunho",
		},
		tabs: {
			general: {
				title: "geral",
				subtabs: {
					dashboard: "painel",
					profile: "perfil",
					statistics: "estatísticas",
					gallery: "galeria",
				},
			},
			addons: {
				title: "addons",
				subtabs: {
					submissions: "envios",
					upload: "enviar",
				},
			},
			review: {
				title: "avaliações",
				subtabs: {
					addons: "addons",
					translations: "traduções",
				},
			},
			posts: {
				title: "publicações",
				subtabs: {
					list: "lista",
					create: "criar",
				},
			},
			database: {
				title: "banco de dados",
				subtabs: {
					contributions: "contribuições",
					users: "usuários",
					textures: "texturas",
					packs: "pacotes",
					files: "arquivos",
					mods: "mods",
					modpacks: "modpacks",
					settings: "configurações",
				},
			},
		},
		months: {
			jan: "Jan",
			january: "Janeiro",
			feb: "Fev",
			february: "Fevereiro",
			mar: "Mar",
			march: "Março",
			apr: "Abr",
			april: "Abril",
			may_: "Mai",
			// longer
			may: "Mai",
			jun: "Jun",
			june: "Junho",
			jul: "Jul",
			july: "Julho",
			aug: "Ago",
			august: "Agosto",
			sep: "Set",
			september: "Setembro",
			oct: "Out",
			october: "Outubro",
			nov: "Nov",
			november: "Novembro",
			dec: "Dez",
			december: "Dezembro",
		},
		json_editor: {
			import_data: "Importar dados em JSON",
			parse_json: "Analisar JSON para dados",
		},
	},
	database: {
		search: "Buscar",
		anonymous: "Anônimo",
		nameless: "Sem nome",
		summary: "Resumo",
		confirm_deletion: "Confirmar exclusão",
		ask_deletion: "Você deseja excluir %s (%d)?",
		contributions: {
			title: "Contribuições",
			contributors: "Contribuidores",
			add_manually: "Adicionar manualmente",
			pack_filter: "Filtrar por pacote",
			user_filter: "Usuários",
			texture_filter: "Texturas",
			select_user: "Selecionar usuário(s)",
			no_contributor_yet: "Nenhum contribuidor ainda",
			contribution_result: "Resultados da contribuição",
			search_contributions: "Buscar contribuições",
			modal: {
				add_new_contribution: "Adicionar uma nova contribuição",
				clone_contribution: "Clonar a contribuição",
				one_contributor: "Por favor escolha pelo menos um contribuidor",
				pack: "Pacote de recursos",
				id_field_errors: {
					one_required: "Pelo menos um ID de textura ou um intervalo de identificação é necessário",
					incorrect_value: "ID ou ID do %value% de textura incorretos",
				},
			},
		},
		users: {
			title: "Usuários",
			role_filter: "Filtrar por função",
			search_username: "Buscar nome de usuário",
			user_result: "Resultados do usuário",
			modal: {
				add_user: "Adicionar novo usuário",
				change_user: "Editar usuário",
				id: "ID do Discord",
				username: "Nome de usuário",
				uuid: "UUID do perfil do Minecraft",
				roles: "Função do usuário",
				anonymous: "Anônimo",
				anonymous_hint:
					'Se marcado, o nome do usuário será exibido como "Anônimo" e sua skin não será exibida. Só pode ser alterado por gerentes!',
			},
		},
		textures: {
			title: "Texturas",
			add_texture: "Adicionar nova textura",
			add_multiple: "Adicionar novas texturas",
			change_texture: "Editar textura",
			deleting_use_will_delete_paths: "Excluindo o uso também irá apagar todos os seus caminhos.",
			texture_result: "Resultados da textura",
			tag_filter: "Filtrar por tag",
			search_texture: "Buscar nome de textura",
			add_success: "Textura(s) adicionada(s) com sucesso",
			modal: {
				title: "Texturas",
				subtitle: "Usos e Caminhos",
				tagless: "Nenhuma tag adicionada",
				copy_json_data: "Dados JSON copiados para área de transferência",
				clear_on_save: "Limpar ao salvar",
				id_hint: "Alterar o ID da textura pode quebrar tudo!",
				id: "ID da textura",
				name: "Nome da textura",
				tags: "Tags da textura",
			},
			uses: {
				title: "Usos",
				singular: "Uso",
				plural: "Usos",
				add_use: "Adicionar novo uso",
				change_use: "Editar uso",
				add_edition_use: "Adicionar uso automático de %edition%",
				no_use_found: "Nenhum uso encontrado para essa textura.",
				id_hint: "Alterar o ID do uso pode quebrar tudo",
				id: "ID do uso",
				name: "Nome do uso",
				edition: "Edição do uso",
			},
			paths: {
				title: "Caminhos",
				singular: "Caminho",
				plural: "Caminhos",
				add_path: "Adicionar novo caminho",
				change_path: "Editar caminho",
				no_path_found: "Nenhum caminho encontrado para esse uso.",
				id_hint: "Alterar o ID do caminho pode quebrar tudo!",
				id: "ID do caminho",
				name_hint: "O caminho deve começar na pasta-mãe (ex: assets/…)",
				name_prefill: "Digite isso primeiro para gerar mais campos!",
				name: "Caminho",
				versions: "Versões",
				mcmeta: "Animado",
			},
			add_version: {
				title: "Adicionar nova versão do Minecraft",
				success: "Versão adicionada com sucesso",
				new_edition: "Edição da nova versão",
				template_version: "Clonar uma versão existente como um modelo",
				new_version: "Nome da nova versão",
			},
			modify_version: {
				title: "Modificar uma versão do Minecraft",
				current_version: "Versão atual do Minecraft",
				new_version: "Nova versão do Minecraft",
				example:
					"Altera todas as instâncias de uma versão do Minecraft no banco de dados para uma diferente. (ex. 1.17 → 1.17.1)",
				warning:
					"Por favor não se esqueça de atualizar todos os nomes das ramificações no GitHub também!",
			},
		},
		packs: {
			title: "Pacotes",
			tag_filter: "Filtrar por tag",
			pack_result: "Resultados do pacote",
			modal: {
				add_pack: "Adicionar novo pacote",
				change_pack: "Editar pacote",
				id: "ID do pacote",
				id_creation_hint:
					"Um ID de Pacote pode ser especificado manualmente ou ser gerado automaticamente.",
				id_editing_hint: "Alterar o ID de um pacote pode quebrar tudo!",
				name: "Nome do pacote",
				tags: "Tags do pacote",
				resolution: "Resolução do pacote",
				logo: "URL do logotipo do pacote",
				github: {
					title: "GitHub",
					title_hint: "Uma edição pode ser deixada em branco se ainda não tiver suporte.",
					length_notice: "Pelo menos um repositório do GitHub precisa estar presente.",
					organization: "Organização",
					repository: "Repositório",
				},
			},
			submissions: {
				title: "Informações de envio",
				add_submission: "Adicionar informações de envio",
				edit_submission: "Editar informações de envio",
				reference_pack: "Pacote de referência",
				reference_hint: "Pacote para comparar com as atribuições de envios.",
				contributor_role: "ID da função do contribuidor",
				time_to_results: "Tempo para os resultados",
				time_hint: "Os atrasos são medidos em dias.",
				channels: {
					title: "Canais do Discord",
					title_hint:
						"Ative o Modo de Desenvolvedor e clique com o botão direito em um canal para obter IDs de canal.",
					submit: "Canal de envio",
					results: "Canal de resultados",
				},
				ask_submission_deletion: "Deseja excluir informações de envio para %s (%d)?",
			},
		},
	},
	review: {
		titles: {
			addons: "Analisar addons",
			translation: "Analisar traduções",
			pending: "Esperando aprovação",
			denied: "Negado",
			approved: "Aprovado",
			archived: "Arquivado",
		},
		deny_window: {
			title: "Negar addon",
			archive_title: "Arquivar add-on",
			label: "Escreva um motivo…",
			rule: "Qualquer motivo pode ser dado",
		},
		labels: {
			pending: "Não há nenhum addon pendente no momento!",
			denied: "Não há nenhum addon negado no momento!",
			archived: "Não há nenhum addon arquivado no momento!",
			approved: "Não há nenhum addon aprovado no momento!",
			load_approved: "Carregar addons aprovados",
		},
		addon: {
			titles: {
				author_singular: "Autor",
				author_plural: "Autor(es)",
				description: "Descrição",
				links: "Links",
				options: "Configurações",
			},
			labels: {
				link: "Link",
				optifine: "OptiFine",
				approved_by: "Aprovado por %s",
				denied_by: "Negado por %s",
				reason: "Motivo",
			},
		},
	},
	addons: {
		titles: {
			submit: "Enviar um novo addon",
			edit: "Editar addon",
			submissions: "Envios de addon",
			details: "Detalhes",
		},
		remove: {
			title: "Confirmar exclusão",
			labels: {
				question: "Você deseja excluir %s?",
				warning: "Não é possível reverter essa operação.",
			},
		},
		general: {
			loading_addon: "Carregando addon",
			rules: "Certifique-se de ler as regras sobre addons antes de enviar",
			title: "Geral",
			name: {
				label: "Nome do addon",
				hint: "É preferível um nome mais curto.",
				rules: {
					name_required: "É necessário um nome.",
					name_too_big: "O nome do addon deve ter menos de %s caracteres.",
					name_too_small: "O nome do addon deve ter no mínimo %s caracteres.",
					name_unavailable: "Este nome já está em uso!",
				},
			},
			description: {
				label: "Descrição do addon",
				hint: "Você pode utilizar a formatação Markdown para melhorar sua descrição!",
				rules: {
					description_required: "A descrição é necessária.",
					description_too_big: "A descrição deve conter menos que %s caracteres.",
					description_too_small: "A descrição deve ter no mínimo %s caracteres.",
				},
			},
			embed_description: {
				label: "Descrição atribuída",
				hint: "Descrição vista ao compartilhar o addon em mídias sociais",
				rules: {
					too_big: "A descrição atribuída deve ser menor que %s caracteres.",
				},
			},
			slug: {
				label: "Slug do addon",
				hint: "Alterar isto quebrará os links antigos!",
			},
			reason: {
				title: "Motivo da atualização",
				text: "Por favor, conte-nos o que você atualizou para tornar a análise do seu addon mais fácil!",
				required: "Uma razão para atualizar é necessária",
				bounds: "Motivo da atualização deve ter entre %s e %s caracteres",
			},
			authors: {
				label: "Selecionar autores do addon",
				hint: "Qualquer autor pode modificar o addon após seu envio! | Se você não encontrar ninguém na lista que deveria estar nela, contate um administrador ou desenvolvedor",
			},
		},
		images: {
			title: "Capturas de tela",
			header: {
				labels: {
					drop: "Clique para selecionar a imagem do cabeçalho",
					normal: "Imagem de cabeçalho",
					replace: "Substituir imagem de cabeçalho",
				},
				rules: {
					image_size:
						"O tamanho da imagem deve ser menor que %s KB! Use https://compressor.io/ para comprimi-la.",
					image_ratio:
						"Proporção errada: a imagem fornecida não tem uma proporção lateral de 16:9.",
					image_required: "Uma imagem de cabeçalho é necessária.",
					jpeg: "A imagem deve ser um JPEG com perdas.",
				},
			},
			carousel: {
				labels: {
					drop: "Clique para selecionar imagens adicionais",
					normal: "Imagem(ns) adicional(is)",
					replace: "Substituir imagem(ns) adicional(is)",
				},
				rule: "Proporção errada: Imagem(ns) sem uma proporção lateral de 16:9 foram removidas.",
			},
		},
		options: {
			title: "Configurações",
			optifine: {
				label: "Requer OptiFine",
			},
			editions: {
				label: "Edição(ões) com suporte",
				rule: "Você precisa selecionar pelo menos 1 edição.",
			},
			resolutions: {
				label: "Resolução(ões) com suporte",
				rule: "Você precisa selecionar pelo menos 1 resolução.",
			},
		},
		downloads: {
			title: "Downloads",
			name: {
				placeholder: "CurseForge, GitHub…",
				label: "Nome",
				rules: {
					name_required: "Um nome é necessário.",
					name_cannot_be_empty: "O nome não pode ser vazio.",
				},
			},
			link: {
				placeholder: "https://www.exemplo.com",
				label: "Link",
				rule: "URL deve ser válido.",
			},
		},
		status: {
			approved: "Aprovado",
			denied: "Negado",
			pending: "Pendente",
			archived: "Arquivado",
		},
	},
	posts: {
		titles: {
			list: "Todas as publicações",
			edit: "Editar publicação",
			new: "Criar nova publicação",
		},
		status: {
			published: "Publicado",
			pending: "Pendente",
		},
		loading: "Carregando publicação…",
		general: {
			heading: "Geral",
			title: {
				label: "Título da publicação",
				placeholder: "Faithful Smart Fridge - Alpha 1",
			},
			permalink: {
				label: "Link permanente",
				placeholder: "/faithfulsmartfridge/A1",
			},
			header_img: {
				label: "Imagem do cabeçalho (opcional)",
				hint: "Nota: Isto deve ser enviado separadamente",
				placeholder: "https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg",
			},
			date: {
				label: "Publicar data de lançamento",
				placeholder: "AAAA-MM-DD",
			},
			description: {
				label: "Descrição da publicação",
				hint: "Você pode usar marcação HTML para melhorar sua descrição!",
			},
		},
		download: {
			heading: "Downloads",
			add_category: "Adicionar categoria de download",
			add_single_item: "Adicionar download único",
			category: "Baixar nome da categoria",
			name: "Nome do download",
			link: "Link de download",
			link_placeholder: "https://www.exemplo.com",
		},
		changelog: {
			heading: "Histórico de mudanças",
			add_category: "Adicionar categoria de histórico de mudanças",
			add_item: "Adicionar item do histórico de mudanças",
			form_levels: {
				primary: "Categoria primária",
				secondary: "Categoria secundária",
				item_category: "Categoria do Item (Autores)",
				item: "Item (Autores)",
			},
		},
	},
	statistics: {
		title: "Estatísticas de contribuição",
		loading: "Carregando gráfico…",
		label: {
			textures: "Texturas",
			contributors: "Contribuidores",
			contributions: "Contribuições",
		},
	},
	profile: {
		title: "Perfil",
		general: {
			title: "Geral",
			uuid: {
				label: "UUID do perfil do Minecraft",
				hint: "Sua skin será exibida com os addons que você fez.",
			},
			username: {
				label: "Nome de usuário",
				hint: "Seu nome de usuário será mostrado e usado no Website em contribuições, addons, etc.",
			},
		},
		social: {
			title: "Links sociais",
			link_label: "Editar link",
			type_label: "Selecionar tipo de mídia",
			placeholder: "https://www.example.com",
			add: "Adicionar rede social",
		},
		save_changes: "Salvar mudanças",
		delete: {
			title: "Excluir conta",
			btn: "Excluir conta",
			description: "Tem certeza que deseja excluir sua conta?",
			warning: "Este processo é irreversível!",
		},
	},
	files: {
		general: {
			name: {
				label: "Nome do arquivo",
				hint: "O nome descreve brevemente o arquivo",
				rules: {
					name_required: "É necessário um nome.",
					name_too_big: "O nome do arquivo deve ter menos de %s caracteres.",
					name_too_small: "O nome do arquivo deve ter pelo menos %s caracteres.",
				},
			},
			use: {
				label: "Uso do arquivo",
				hint: "Descreva brevemente o uso",
				rules: {
					name_required: "É necessário um valor.",
					name_too_big: "O uso do arquivo deve ter menos de %s caracteres.",
					name_too_small: "Uso do arquivo deve ter pelo menos %s caracteres.",
				},
			},
		},
	},
	gallery: {
		stretched_switcher: "Visualização completa de largura",
		share_link_copied_to_clipboard: "Link de compartilhamento copiado para a área de transferência",
		max_items_per_row: "Máximo de itens por linha",
		title: "Galeria",
		loading_message: "Carregando…",
		error_message: {
			texture_not_done: "Textura não concluída!",
			user_anonymous: "Anônimo",
			user_not_found: "Usuário desconhecido",
			contribution_not_found: "Nenhuma contribuição encontrada no banco de dados!",
			search_failed: "Falha ao pesquisar",
		},
		category: {
			search: "Buscar",
			tag: "Tags",
			mc_version: "Versão do Minecraft",
			edition: "Edição",
			pack: "Pacote",
		},
		sort: {
			name_asc: "Nome (A → Z)",
			name_desc: "Nome (Z → A)",
			id_asc: "ID de Textura (menor → maior)",
			id_desc: "ID de textura (maior → menor)",
			contrib_desc: "Contribuição Recente",
		},
		tooltip: {
			modded: "Textura modificada",
			mojang: "Mojang Studios",
			ignored: "Textura ignorada",
		},
		all: "Tudo",
		latest: "Mais recentes",
		clear_cache: "Limpar Cache da Galeria",
		result_stats_singular: "Textura %COUNT% encontrada em %SECONDS% segundos",
		result_stats_plural: "Texturas %COUNT% encontradas em %SECONDS% segundos",
		modal: {
			no_contributions: "Nenhuma contribuição encontrada",
			tabs: {
				information: "informações",
				authors: "autores",
			},
			info: {
				texture: "Textura",
				uses: "Usos",
				paths: "Caminhos",
			},
			data: {
				contribution_id: "ID de contribuição",
				date: "Data",
				authors: "Autor(es)",
				id: "ID",
				name: "Nome",
				tags: "Tags/Tipos",
				use_id: "ID do uso",
				use_name: "Nome do uso",
				edition: "Edição",
				texture_id: "ID da textura",
				path_id: "ID do caminho",
				resource_pack_path: "Caminho do pacote de recursos",
				mc_versions: "Versão(ões) do Minecraft",
			},
		},
	},
	settings: {
		title: "Configurações",
		label: {
			edit_raw: "Editar JSON bruto",
			edit_editor: "Edite com editor visual",
		},
	},
	dashboard: {
		welcome_user: "Bem-vindo, %USER%!",
		welcome: "Bem-vindo!",
		totals: {
			authors: "autores",
			contributions: "contribuições",
			last_day: "contribuições nas últimas 48 horas",
			last_week: "contribuições na última semana",
			last_month: "contribuições no último mês",
		},
		titles: {
			users: "Usuários",
			addons: "Add-ons",
			contribution_activity: "Atividade de contribuição",
			contribution_stats: "Contribuições",
			profile: "Perfil",
		},
		addons: {
			submissions: "Envios",
			upload: "Enviar",
		},
		users: {
			total: "usuários",
			total_anonymous: "anônimo",
			total_roles: "funções",
		},
		locale: {
			on: "ligado",
			less: "Menos",
			more: "Mais",
		},
	},
	missing_page: {
		title: "Você está perdido no Fim?",
		description: "Infelizmente, a página que você solicitou não existe!",
		main_page:
			"Tente verificar a ortografia ou ir para a página %main % para encontrar o que estava procurando.",
	},
	datepicker: {
		year: "Ano",
		month: "Mês",
		day: "Dia",
	},
};
