/**
 * This file is the template for all other languages
 */

export default {
 global: {
  name: 'Faithful Web Application',
  logout: 'Sair',
  login: 'Entrar com Discord',
  ends_success: 'Sucesso',
  loading: 'Carregando, aguarde…',
  no_results: 'Nenhum resultado encontrado',
  nyi: 'Não implementado ainda.',
  translations: 'Translations',
  snackbar_system_theme: {
   sentence: 'System theme changed to %s',
   themes: {
    title: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
   },
  },
  btn: {
   add: 'Adicionar',
   add_download: 'Adicionar download',
   submit: 'Enviar',
   submit_and_approve: 'Submit and approve',
   cancel: 'Cancelar',
   close: 'Fechar',
   save: 'Salvar',
   edit: 'Editar',
   delete: 'Excluir',
   ok: 'OK',
   yes: 'Sim',
   deny: 'Negar',
   approve: 'Aprovar',
   archive: 'Archive',
   load_more: 'Carregar mais',
   discard: 'Discard',
   confirm: 'Confirm',
   publish: 'Publish',
   save_draft: 'Save as draft',
  },
  tabs: {
   general: {
    title: 'general',
    subtabs: {
     dashboard: 'dashboard',
     profile: 'perfil',
     statistics: 'estatísticas',
     gallery: 'galeria',
    },
   },
   addons: {
    title: 'add-ons',
    subtabs: {
     submissions: 'enviados',
     upload: 'enviar',
    },
   },
   review: {
    title: 'reviews',
    subtabs: {
     addons: 'add-ons',
     translations: 'traduções',
    },
   },
   posts: {
    title: 'posts',
    subtabs: {
     list: 'list',
     create: 'create',
    },
   },
   database: {
    title: 'banco de dados',
    subtabs: {
     contributions: 'contribuições',
     users: 'users',
     textures: 'texturas',
     packs: 'packs',
     files: 'files',
     mods: 'mods',
     modpacks: 'modpacks',
     settings: 'settings',
    },
   },
  },
  months: {
   jan: 'Jan',
   january: 'Janeiro',
   feb: 'Fev',
   february: 'Fevereiro',
   mar: 'Mar',
   march: 'Março',
   apr: 'Abr',
   april: 'Abril',
   may_: 'Mai',
   // longer
   may: 'Mai',
   jun: 'Jun',
   june: 'Junho',
   jul: 'Jul',
   july: 'Julho',
   aug: 'Ago',
   august: 'Agosto',
   sep: 'Set',
   september: 'Setembro',
   oct: 'Out',
   october: 'Outubro',
   nov: 'Nov',
   november: 'Novembro',
   dec: 'Dez',
   december: 'Dezembro',
  },
 },
 database: {
  titles: {
   contributions: 'Contribuições',
   contributors: 'Contribuidores',
   textures: 'Texturas',
   users: 'Users',
   packs: 'Packs',
   add_user: 'Adicionar novo contribuidor',
   add_textures: 'Adicionar novas texturas',
   add_texture: 'Adicionar nova textura',
   add_pack: 'Add new pack',
   change_pack: 'Edit pack',
   add_submission: 'Add submission information',
   edit_submission: 'Edit submission information',
   add_use: 'Adicionar novo uso',
   add_path: 'Adicionar novo caminho',
   add_mc_version: 'Adicionar nova versão do Minecraft',
   change_path: 'Editar caminho',
   change_use: 'Editar uso',
   change_texture: 'Editar textura',
   change_user: 'Editar contribuidor',
   change_mc_version: 'Modificar uma versão do Minecraft',
   confirm_deletion: 'Confirmar exclusão',
  },
  subtitles: {
   add_manually: 'Adicionar manualmente',
   add_new_contribution: 'Add a new contribution',
   clone_contribution: 'Clone the contribution',
   no_contributor_yet: 'No contributor yet',
   pack: 'Resource Pack',
   submissions: 'Submission information',
   github: 'GitHub',
   resource_packs: 'Filter by pack',
   channels: 'Discord channels',
   user: 'Contribuidor',
   select_user_role: 'Selecionar o tipo de contribuidor',
   search: 'Buscar',
   texture_result: 'Resultados da textura',
   pack_result: 'Pack results',
   user_result: 'User results',
   contribution_result: 'Contribution results',
   import_json_data: 'Importar dados em JSON',
   uses: 'Uso(s)',
   paths: 'Caminho(s)',
  },
  labels: {
   copy_json_data: 'Copied JSON data to clipboard',
   anonymous: 'Anonymous',
   anonymous_explain:
    'If checked, the user\'s name will be displayed as "Anonymous" and their skin won\'t show up. Can only be changed by managers!',
   mcmeta: 'Animated',
   new_mc_version_edition: 'Edição a adicionar a versão',
   new_mc_version_path: 'Versão do caminho a adicionar a versão',
   new_mc_version_name: 'Novo nome de versão',
   nameless: 'Sem nome',
   tagless: 'No tags added',
   add_textures_success: 'Texturas adicionadas com sucesso',
   add_version_success: 'Versão adicionada com sucesso',
   add_new_user: 'Adicionar novo contribuidor',
   add_new_pack: 'Add new pack',
   add_new_texture: 'Adicionar nova textura',
   add_new_path: 'Adicionar novo caminho',
   add_new_use: 'Adicionar novo uso',
   add_edition_use: 'Add automatic %edition% use',
   add_texture: 'Adicionar texturas',
   add_mc_version: 'Adicionar nova versão do Minecraft',
   ask_deletion: 'Você deseja excluir %s (%d)?',
   ask_submission_deletion: 'Do you want to delete submission information for %s (%d)?',
   close_on_submit: 'Close on submit',
   clear_on_save: 'Clear on save',
   user_role: 'Tipo do contribuidor',
   discord_id: 'ID do Discord',
   pack_id: 'Pack ID',
   pack_name: 'Pack name',
   pack_tags: 'Pack tags',
   pack_resolution: 'Pack resolution',
   pack_logo: 'Pack logo URL',
   council_enabled: 'Enable council',
   contributor_role: 'Contributor role ID',
   time_to_results: 'Time to results',
   time_to_council: 'Time to council',
   channels: {
    submit: 'Submission channel',
    council: 'Council channel',
    results: 'Results channel',
   },
   github_org: 'Organization',
   github_repo: 'Repository',
   submission_reference: 'Reference pack',
   edit_submission: 'Edit submission information',
   invalid_url: 'This URL is not valid',
   new_submission: 'Enable submissions',
   edit_mc_version: 'Modificar uma versão do Minecraft',
   one_contributor: 'Por favor escolha pelo menos um contribuidor',
   select_user: 'Select user(s)',
   parse_json: 'Analisar JSON para dados',
   search_contributions: 'Buscar contribuições',
   search_username: 'Buscar nome de usuário',
   search_texture: 'Buscar nome de textura',
   search_pack: 'Search packs',
   select_texture_tag: 'Selecionar tipo de textura',
   select_pack_tag: 'Filter by tag',
   username: 'Nome de usuário',
   uuid: 'UUID do perfil do Minecraft',
   texture_name: 'Nome da textura',
   texture_tags: 'Tipo da textura',
   texture_id: 'ID da textura',
   texture_uses: 'Uso(s) da textura',
   use_name: 'Nome do uso',
   use_id: 'ID do uso',
   use_edition: 'Edição do uso',
   path: 'Caminho',
   path_id: 'ID do caminho',
   versions: 'Versões',
   no_path_found: 'Nenhum caminho encontrado para esse uso.',
   no_use_found: 'Nenhum uso encontrado para essa textura.',
   current_mc_version: 'Versão atual do Minecraft',
   new_mc_version: 'Nova versão do Minecraft',
   id_field_errors: {
    one_required: 'At least one texture ID or an ID range is required',
    incorrect_value: 'Incorrect texture %value% ID or ID range',
   },
   use_singular: 'Use',
   use_plural: 'Uses',
   path_singular: 'Path',
   path_plural: 'Paths',
  },
  hints: {
   pack_id_creation: 'A Pack ID can either be manually specified or automatically generated.',
   pack_id_editing: 'Changing a pack ID can break everything!',
   pack_reference: 'Pack to compare against in submission embeds.',
   submission_timings: 'Delays are measured in days.',
   github_required: "An edition can be left blank if it's not yet supported.",
   channel_ids: 'Enable Developer Mode and right click on a channel to get channel IDs.',
   texture_id: 'Alterar o ID da textura pode quebrar tudo',
   use_id: 'Alterar o ID do uso pode quebrar tudo',
   path_id: 'Alterar o ID do caminho pode quebrar tudo',
   path_prefill: 'Enter this first to generate most fields!',
   path: 'O caminho deve começar na pasta-mãe (ex.: assets/…)',
   example_scenario:
    'Altera todas as instâncias de uma versão do Minecraft no banco de dados para uma diferente. (ex.: 1.17 → 1.17.1)',
   example_scenario_warn: 'Por favor não se esqueça de atualizar todos os nomes das ramificações no GitHub também!',
  },
  messages: {
   deleting_use_will_delete_paths: 'Deleting the use will also delete all its paths.',
  },
 },
 review: {
  titles: {
   addons: 'Analisar add-ons',
   translation: 'Analisar traduções',
   pending: 'Esperando aprovação',
   denied: 'Negado',
   approved: 'Aprovado',
   archived: 'Archived',
  },
  deny_window: {
   title: 'Deny add-on',
   label: 'Escreva um motivo…',
   rule: 'Qualquer motivo pode ser dado',
  },
  labels: {
   pending: 'Não há nenhum add-on pendente no momento!',
   denied: 'Não há nenhum add-on negado no momento!',
   archived: 'There are currently no archived add-ons!',
   approved: 'There are current no approved add-ons!',
   load_approved: 'Carregar add-ons aprovados',
  },
  addon: {
   titles: {
    authors: 'Autor(es)',
    description: 'Descrição',
    links: 'Links',
    options: 'Configurações',
   },
   labels: {
    link: 'Link',
    optifine: 'OptiFine',
    approved_by: 'Aprovado por',
    denied_by: 'Negado por',
    reason: 'Motivo',
   },
  },
 },
 addons: {
  titles: {
   submit: 'Enviar um novo add-on',
   edit: 'Edit add-on',
   submissions: 'Enviados',
   details: 'Details',
  },
  remove: {
   title: 'Confirmar exclusão',
   labels: {
    question: 'Você deseja excluir %s?',
    warning: 'Não é possível reverter essa operação.',
   },
  },
  general: {
   loading_addon: 'Loading add-on',
   rules: 'Make sure to read the add-on rules before submitting',
   title: 'Geral',
   name: {
    label: 'Add-on name',
    hint: 'A shorter name is preferred.',
    rules: {
     name_required: 'A name is required.',
     name_too_big: 'Add-on name must be less than %s characters.',
     name_too_small: 'Add-on name must be at least %s characters long.',
     name_unavailable: 'This name is already taken!',
    },
   },
   description: {
    label: 'Descrição do add-on',
    hint: 'Você pode utilizar a formatação Markdown para melhorar sua descrição!',
    rules: {
     description_required: 'A descrição é necessária.',
     description_too_big: 'A descrição deve conter menos que %s caracteres.',
     description_too_small: 'Description must be at least %s characters long.',
    },
   },
   embed_description: {
    label: 'Embed description',
    hint: 'Description seen when sharing the add-on on social media',
    rules: {
     too_big: 'Embed description must be less than %s characters.',
    },
   },
   slug: {
    label: 'Add-on slug',
    hint: 'Changing this will break old links!',
   },
   reason: {
    title: 'Update reason',
    text: 'Please tell us what you updated to make reviewing your add-on easier!',
    required: 'An update reason is required',
    bounds: 'Update reason must be between %s and %s characters long',
   },
   authors: {
    label: 'Selecionar autores do add-on',
    hint:
     'Qualquer autor pode modificar o add-on após seu envio! | Se você não encontrar ninguém na lista que deveria estar nela, contate um administrador/desenvolvedor',
   },
  },
  images: {
   title: 'Imagens',
   header: {
    labels: {
     drop: 'Clique para selecionar a imagem do cabeçalho',
     normal: 'Imagem de cabeçalho',
     replace: 'Substituir imagem de cabeçalho',
    },
    rules: {
     image_size: 'O tamanho da imagem deve ser menor que %s KB! Use https://compressor.io/ para comprimi-la.',
     image_ratio: 'Proporção errada: a imagem fornecida não tem uma proporção lateral de 16:9.',
     image_required: 'Uma imagem de cabeçalho é necessária.',
     jpeg: 'Image must be a lossy JPEG.',
    },
   },
   carousel: {
    labels: {
     drop: 'Clique para selecionar imagens adicionais',
     normal: 'Imagem(ns) adicional(is)',
     replace: 'Substituir imagem(ns) adicional(is)',
    },
    rule: 'Proporção errada: Imagem(ns) sem uma proporção lateral de 16:9 foram removidas.',
   },
  },
  options: {
   title: 'Configurações',
   optifine: {
    label: 'Requer OptiFine',
   },
   editions: {
    label: 'Edição(ões) suportada(s)',
    rule: 'Você precisa selecionar pelo menos 1 edição.',
   },
   resolutions: {
    label: 'Resolução(ões) suportada(s)',
    rule: 'Você precisa selecionar pelo menos 1 resolução.',
   },
  },
  downloads: {
   title: 'Downloads',
   name: {
    placeholder: 'CurseForge, GitHub…',
    label: 'Nome',
    rules: {
     name_required: 'Um nome é necessário..',
     name_cannot_be_empty: 'O nome não pode ser vazio.',
    },
   },
   link: {
    placeholder: 'https://www.example.com/',
    label: 'Link',
    rule: 'URL deve ser válido.',
   },
  },
  status: {
   approved: 'Aprovado',
   denied: 'Negado',
   pending: 'Pendente',
  },
 },
 posts: {
  titles: {
   list: 'All posts',
   edit: 'Edit post',
   new: 'Create new post',
  },
  status: {
   published: 'Published',
   pending: 'Pending',
  },
  loading: 'Loading post…',
  general: {
   heading: 'General',
   title: {
    label: 'Post title',
    placeholder: 'Faithful Smart Fridge – Alpha 1',
   },
   permalink: {
    label: 'Permalink',
    placeholder: '/faithfulsmartfridge/A1',
   },
   header_img: {
    label: 'Header image (optional)',
    hint: 'Note: This must be uploaded separately',
    placeholder: 'https://database.faithfulpack.net/images/website/posts/fridge/A1.jpg',
   },
   date: {
    label: 'Post release date',
    placeholder: 'YYYY-MM-DD',
   },
   description: {
    label: 'Post description',
    hint: 'You can use HTML markup to improve your description!',
   },
  },
  download: {
   heading: 'Downloads',
   add_category: 'Add download category',
   add_single_item: 'Add single download',
   category: 'Download category name',
   name: 'Download name',
   link: 'Download link',
   link_placeholder: 'https://www.example.com/',
  },
  changelog: {
   heading: 'Changelog',
   add_category: 'Add changelog category',
   add_item: 'Add changelog item',
   form_levels: {
    primary: 'Primary category',
    secondary: 'Secondary category',
    item_category: 'Item category (Authors)',
    item: 'Item (Authors)',
   },
  },
 },
 statistics: {
  title: 'Estatísticas de contribuição',
  loading: 'Loading graph…',
  label: {
   textures: 'Texturas',
   contributors: 'Contribuidores',
   contributions: 'Contribuições',
  },
 },
 profile: {
  title: 'Perfil',
  general: {
   title: 'Geral',
   uuid: {
    label: 'UUID do perfil do Minecraft',
    hint: 'Your skin will be displayed with add-ons you authored.',
   },
   username: {
    label: 'Nome de usuário',
    hint: 'Seu nome de usuário será mostrado e usado no Website em contribuições, add-ons etc.',
   },
  },
  social: {
   title: 'Links sociais',
   link_label: 'Edit link',
   type_label: 'Select media type',
   placeholder: 'https://www.example.com/',
   add: 'Add social media',
  },
  save_changes: 'Save changes',
  delete: {
   title: 'Delete account',
   btn: 'Delete account',
   description: 'Are you sure you want to delete your account?',
   warning: 'This process is irreversible!',
  },
 },
 files: {
  general: {
   name: {
    label: 'File name',
    hint: 'Name describes shortly the file',
    rules: {
     name_required: 'A name is required.',
     name_too_big: 'File name must be less than %s characters.',
     name_too_small: 'File name must be at least %s characters long.',
    },
   },
   use: {
    label: 'File use',
    hint: 'Describes short use',
    rules: {
     name_required: 'A value is required.',
     name_too_big: 'File use must be less than %s characters.',
     name_too_small: 'File use must be at least %s characters long.',
    },
   },
  },
 },
 gallery: {
  stretched_switcher: 'Full width view',
  share_link_copied_to_clipboard: 'Share link copied to clipboard',
  max_items_per_row: 'Max items per row',
  title: 'Galeria',
  loading_message: 'Carregando…',
  error_message: {
   texture_not_done: 'Textura não concluída!',
   user_anonymous: 'Anonymous',
   user_not_found: 'Usuário desconhecido',
   contribution_not_found: 'Nenhuma contribuição encontrada no banco de dados!',
  },
  category: {
   search: 'Buscar',
   tag: 'Tags',
   mc_version: 'Versão do Minecraft',
   edition: 'Edição',
   pack: 'Pack',
  },
  sort: {
   name_asc: 'Name (A → Z)',
   name_desc: 'Name (Z → A)',
   id_asc: 'Texture ID (smallest → largest)',
   id_desc: 'Texture ID (largest → smallest)',
   contrib_desc: 'Recently Contributed',
  },
  tooltip: {
   modded: 'Modded Texture',
   mojang: 'Mojang Studios',
   ignored: 'Ignored Texture',
  },
  all: 'All',
  latest: 'Latest',
  clear_cache: 'Clear Gallery Cache',
  result_stats_singular: '%COUNT% texture found in %SECONDS% seconds',
  result_stats_plural: '%COUNT% textures found in %SECONDS% seconds',
  modal: {
   no_contributions: 'No contributions found',
   tabs: {
    information: 'informações',
    authors: 'autores',
   },
   info: {
    texture: 'Textura',
    uses: 'Usos',
    paths: 'Caminhos',
   },
   data: {
    contribution_id: 'Contribution ID',
    date: 'Data',
    authors: 'Autor(es)',
    id: 'ID',
    name: 'Nome',
    tags: 'Tags/Tipos',
    use_id: 'ID do uso',
    use_name: 'Nome do uso',
    edition: 'Edição',
    texture_id: 'ID da textura',
    path_id: 'ID do caminho',
    resource_pack_path: 'Caminho do pacote de recursos',
    mc_versions: 'Versão(ões) do Minecraft',
   },
  },
 },
 settings: {
  title: 'Settings',
  label: {
   edit_raw: 'Edit raw JSON',
   edit_editor: 'Edit with visual editor',
  },
 },
 dashboard: {
  welcome_user: 'Welcome %USER%!',
  welcome: 'Welcome!',
  totals: {
   authors: 'authors',
   contributions: 'contributions',
   last_day: 'contributions in the last 48 hours',
   last_week: 'contributions last week',
   last_month: 'contributions last month',
  },
  titles: {
   users: 'Users',
   addons: 'Add-ons',
   contribution_activity: 'Contribution Activity',
   contribution_stats: 'Contributions',
   profile: 'Profile',
  },
  addons: {
   submissions: 'Submissions',
   upload: 'Upload',
  },
  users: {
   total: 'users',
   total_anonymous: 'anonymous',
   total_roles: 'roles',
  },
  locale: {
   on: 'on',
   less: 'Less',
   more: 'More',
  },
 },
 missing_page: {
  title: 'Are you lost in The End?',
  description: "Unfortunately, the page you requested doesn't exist!",
  main_page: 'Try checking your spelling or going to the %main page% to find what you were looking for.',
 },
 datepicker: {
  year: 'Year',
  month: 'Month',
  day: 'Day',
 },
};
